In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

from pathlib import Path

In [15]:
# ============================================================
# 1. LOAD BOTH RESULT FILES
# ============================================================

csv_a = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/larryhh-arm64/wi_experiment.csv")
csv_b = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/root-x86_64/wi_experiment.csv")

df_a = pd.read_csv(csv_a)
df_b = pd.read_csv(csv_b)

print("Loaded files:")
print(f"  A: {csv_a} -> {df_a.shape}")
print(f"  B: {csv_b} -> {df_b.shape}")
print()

print("Column equality check:")
print(df_a.columns.tolist() == df_b.columns.tolist())
print()

if df_a.columns.tolist() != df_b.columns.tolist():
    print("Columns in A not in B:", sorted(set(df_a.columns) - set(df_b.columns)))
    print("Columns in B not in A:", sorted(set(df_b.columns) - set(df_a.columns)))
    raise ValueError("CSV schemas do not match. Fix this before merging.")

# ============================================================
# 2. MERGE + DEDUPLICATE
# ============================================================

df = pd.concat([df_a, df_b], ignore_index=True)
print(f"Concatenated shape: {df.shape}")

# Drop exact duplicate rows first
df = df.drop_duplicates()
print(f"After exact row deduplication: {df.shape}")

# Optional stronger deduplication:
# keep last row for same experimental identity
dedup_cols = [
    "seed",
    "model_type",
    "dataset_name",
    "ansatz",
    "batch_size",
    "epochs",
    "input_dim",
    "depth",
    "num_classes",
]

# Convert datetime so that "keep=last" is meaningful
df["datetime"] = pd.to_datetime(df["datetime"], errors="coerce")
df = df.sort_values("datetime").drop_duplicates(subset=dedup_cols, keep="last")
print(f"After experiment-identity deduplication: {df.shape}")
print()

# ============================================================
# 3. BASIC SANITY CHECKS
# ============================================================

print("Unique datasets:")
print(sorted(df["dataset_name"].dropna().unique()))
print()

print("Unique model types:")
print(sorted(df["model_type"].dropna().unique()))
print()

print("Unique input_dim values:")
print(sorted(df["input_dim"].dropna().unique()))
print()

print("Seeds present:")
print(sorted(df["seed"].dropna().astype(int).unique()))
print()

print("Unique ansatz values:")
for a in sorted(df["ansatz"].dropna().unique()):
    print(" ", a)
print()

# ============================================================
# 4. KEEP QUANTUM RUNS ONLY
# ============================================================

qdf = df[df["model_type"] == "quantum"].copy()
print(f"Quantum-only shape: {qdf.shape}")
print()

# ============================================================
# 5. PARSE LOSS CURVES
# ============================================================

def parse_loss_list(x):
    if pd.isna(x):
        return None
    if isinstance(x, list):
        return x
    if isinstance(x, str):
        try:
            return json.loads(x)
        except Exception:
            return None
    return None

qdf["train_losses_parsed"] = qdf["train_losses"].apply(parse_loss_list)
qdf["val_losses_parsed"] = qdf["val_losses"].apply(parse_loss_list)

# ============================================================
# 6. COVERAGE TABLE: WHAT SETTINGS HAVE HOW MANY RUNS?
# ============================================================

coverage = (
    qdf.groupby(["dataset_name", "input_dim", "ansatz"])
       .agg(
           n_runs=("seed", "count"),
           seeds=("seed", lambda x: sorted(set(int(v) for v in x if pd.notna(v))))
       )
       .reset_index()
       .sort_values(["dataset_name", "input_dim", "ansatz"])
)

print("===== COVERAGE =====")
print(coverage.to_string(index=False))
print()

print("===== COVERAGE COUNTS BY DATASET / INPUT_DIM =====")
print(
    coverage.groupby(["dataset_name", "input_dim"])["n_runs"]
            .agg(["count", "min", "max"])
            .reset_index()
            .to_string(index=False)
)
print()

# ============================================================
# 7. MAIN SUMMARY TABLE
# ============================================================

summary = (
    qdf.groupby(["dataset_name", "input_dim", "ansatz"])
       .agg(
           n_runs=("test_f1", "count"),
           acc_mean=("test_acc", "mean"),
           acc_std=("test_acc", "std"),
           prec_mean=("test_prec", "mean"),
           prec_std=("test_prec", "std"),
           rec_mean=("test_rec", "mean"),
           rec_std=("test_rec", "std"),
           f1_mean=("test_f1", "mean"),
           f1_std=("test_f1", "std"),
           loss_mean=("test_loss", "mean"),
           loss_std=("test_loss", "std"),
           time_mean=("average_time_per_epoch", "mean"),
           time_std=("average_time_per_epoch", "std"),
       )
       .reset_index()
       .sort_values(["dataset_name", "input_dim", "f1_mean"], ascending=[True, True, False])
)

print("===== FULL SUMMARY =====")
print(summary.to_string(index=False))
print()

# ============================================================
# 8. ONLY FULL 5-SEED SETTINGS
# ============================================================

summary5 = summary[summary["n_runs"] == 5].copy()

print("===== 5-SEED SUMMARY ONLY =====")
print(summary5.to_string(index=False))
print()

print("===== 5-SEED COUNTS BY DATASET / INPUT_DIM =====")
print(
    summary5.groupby(["dataset_name", "input_dim"]).size()
            .reset_index(name="num_methods")
            .to_string(index=False)
)
print()

# ============================================================
# 9. PRINT PER-DATASET TABLES
# ============================================================

for ds in sorted(summary5["dataset_name"].unique()):
    print(f"\n===== {ds.upper()} : 5-SEED SETTINGS =====")
    sub = summary5[summary5["dataset_name"] == ds].sort_values(
        ["input_dim", "f1_mean"], ascending=[True, False]
    )
    print(sub.to_string(index=False))

# ============================================================
# 10. TOP METHODS PER DATASET / INPUT_DIM
# ============================================================

topk = (
    summary5.sort_values(["dataset_name", "input_dim", "f1_mean"], ascending=[True, True, False])
            .groupby(["dataset_name", "input_dim"])
            .head(5)
            .copy()
)

print("\n===== TOP 5 METHODS PER DATASET / INPUT_DIM (BY F1) =====")
print(topk.to_string(index=False))
print()

# ============================================================
# 11. SAVE MERGED + SUMMARIZED OUTPUTS
# ============================================================

out_dir = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis")
out_dir.mkdir(parents=True, exist_ok=True)

merged_csv = out_dir / "wi_experiment_merged.csv"
coverage_csv = out_dir / "coverage.csv"
summary_csv = out_dir / "summary_all.csv"
summary5_csv = out_dir / "summary_5seed.csv"
topk_csv = out_dir / "top5_by_dataset_inputdim.csv"

df.to_csv(merged_csv, index=False)
coverage.to_csv(coverage_csv, index=False)
summary.to_csv(summary_csv, index=False)
summary5.to_csv(summary5_csv, index=False)
topk.to_csv(topk_csv, index=False)

print("Saved:")
print(" ", merged_csv)
print(" ", coverage_csv)
print(" ", summary_csv)
print(" ", summary5_csv)
print(" ", topk_csv)
print()

# ============================================================
# 12. OPTIONAL: BUILD A SMALL PAPER-FACING TABLE CANDIDATE
#     Edit keep_methods / keep_dims after inspecting summary5
# ============================================================

keep_methods = [
    "HEA (y, z)",
    "Random PQC",
    "MPS (d=1)",
    "MPS (d=2)",
    "MPS (d=3)",
    "TTN (d=1)",
    "TTN (d=2)",
    "TTN (d=3)",
    "WI-PQC (E) (greedy)",
    "WI-PQC (E) (greedy, top_half)",
    "WI-PQC (E) (greedy, cosine_norm)",
    "WI-PQC (E) (mwst, cosine_norm)",
    "WI-PQC (W+E, chunking)",
    "WI-PQC (W+E, svd)",
    "WI-PQC (W1+W2+E, chunking)",
    "WI-PQC (W1+W2+E, svd)",
]

paper_candidates = summary5[summary5["ansatz"].isin(keep_methods)].copy()

print("===== PAPER CANDIDATES (5-SEED ONLY) =====")
print(
    paper_candidates.sort_values(["dataset_name", "input_dim", "f1_mean"], ascending=[True, True, False])
                    .to_string(index=False)
)
print()

paper_candidates_csv = out_dir / "paper_candidates_5seed.csv"
paper_candidates.to_csv(paper_candidates_csv, index=False)
print("Saved:", paper_candidates_csv)
print()

# ============================================================
# 13. OPTIONAL: MEAN LOSS CURVE EXTRACTION
#     Change dataset_name / input_dim / ansatz_name as needed
# ============================================================

def mean_curve(curves):
    curves = [c for c in curves if isinstance(c, list) and len(c) > 0]
    if len(curves) == 0:
        return None, None
    min_len = min(len(c) for c in curves)
    arr = np.array([c[:min_len] for c in curves], dtype=float)
    return arr.mean(axis=0), arr.std(axis=0)

dataset_name = "iris"
input_dim = 4
ansatz_name = "WI-PQC (W1+W2+E, chunking)"

subset = qdf[
    (qdf["dataset_name"] == dataset_name) &
    (qdf["input_dim"] == input_dim) &
    (qdf["ansatz"] == ansatz_name)
].copy()

train_mean, train_std = mean_curve(subset["train_losses_parsed"].tolist())
val_mean, val_std = mean_curve(subset["val_losses_parsed"].tolist())

print(f"===== LOSS CURVE CHECK: {dataset_name}, {input_dim}q, {ansatz_name} =====")
print("n_rows:", len(subset))
print("train_mean:", train_mean)
print("val_mean:", val_mean)

# Save one example curve if available
if train_mean is not None and val_mean is not None:
    curve_df = pd.DataFrame({
        "epoch": np.arange(1, len(train_mean) + 1),
        "train_mean": train_mean,
        "train_std": train_std,
        "val_mean": val_mean,
        "val_std": val_std,
    })
    curve_csv = out_dir / f"curve_{dataset_name}_{input_dim}q_{ansatz_name.replace('/', '-').replace(' ', '_')}.csv"
    curve_df.to_csv(curve_csv, index=False)
    print("Saved example curve:", curve_csv)
else:
    print("No valid loss curves found for that selection.")

Loaded files:
  A: /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/larryhh-arm64/wi_experiment.csv -> (416, 28)
  B: /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/root-x86_64/wi_experiment.csv -> (170, 28)

Column equality check:
True

Concatenated shape: (586, 28)
After exact row deduplication: (586, 28)
After experiment-identity deduplication: (564, 28)

Unique datasets:
['diabetes', 'iris', 'wine']

Unique model types:
['classical', 'quantum']

Unique input_dim values:
[4, 6, 8]

Seeds present:
[0, 1, 2, 3, 4]

Unique ansatz values:
  HEA (y, z)
  MPS (d=1)
  MPS (d=2)
  MPS (d=3)
  Random PQC
  TTN (d=1)
  TTN (d=2)
  TTN (d=3)
  WI-PQC (E) (greedy)
  WI-PQC (E) (greedy, cosine_norm)
  WI-PQC (E) (greedy, top_half)
  WI-PQC (E) (mwst, cosine_norm)
  WI-PQC (W+E, chunking)
  WI-PQC (W+E, svd)
  WI-PQC (W1+W2+E, chunking)
  WI-PQC (W1+W2+E, svd)

Quantum-only shape: (530, 28)

===== COVERAGE =====
dataset_name  input_dim                           ansatz  n_runs           seeds
    diabetes          4                       HEA (y, z)       5 [0, 1, 2, 3, 4]
    diabetes          4                        MPS (d=1)       5 [0, 1, 2, 3, 4]
    diabetes          4                        MPS (d=2)       5 [0, 1, 2, 3, 4]
    diabetes          4                        MPS (d=3)       5 [0, 1, 2, 3, 4]
    diabetes          4                       Random PQC       5 [0, 1, 2, 3, 4]
    diabetes          4                        TTN (d=1)       5 [0, 1, 2, 3, 4]
    diabetes          4                        TTN (d=2)       5 [0, 1, 2, 3, 4]
    diabetes          4                        TTN (d=3)       5 [0, 1, 2, 3, 4]
    diabetes          4              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
    diabetes          4 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
    diabetes          4    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
    diabetes          4   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
    diabetes          4           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
    diabetes          4                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
    diabetes          4       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
    diabetes          4            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]
    diabetes          6                       HEA (y, z)       5 [0, 1, 2, 3, 4]
    diabetes          6                        MPS (d=1)       5 [0, 1, 2, 3, 4]
    diabetes          6                        MPS (d=2)       5 [0, 1, 2, 3, 4]
    diabetes          6                        MPS (d=3)       5 [0, 1, 2, 3, 4]
    diabetes          6                       Random PQC       5 [0, 1, 2, 3, 4]
    diabetes          6              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
    diabetes          6 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
    diabetes          6    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
    diabetes          6   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
    diabetes          6           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
    diabetes          6                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
    diabetes          6       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
    diabetes          6            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]
    diabetes          8                       HEA (y, z)       5 [0, 1, 2, 3, 4]
    diabetes          8                        MPS (d=1)       5 [0, 1, 2, 3, 4]
    diabetes          8                        MPS (d=2)       5 [0, 1, 2, 3, 4]
    diabetes          8                        MPS (d=3)       5 [0, 1, 2, 3, 4]
    diabetes          8                       Random PQC       5 [0, 1, 2, 3, 4]
    diabetes          8                        TTN (d=1)       5 [0, 1, 2, 3, 4]
    diabetes          8                        TTN (d=2)       5 [0, 1, 2, 3, 4]
    diabetes          8                        TTN (d=3)       5 [0, 1, 2, 3, 4]
    diabetes          8              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
    diabetes          8 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
    diabetes          8    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
    diabetes          8   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
    diabetes          8           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
    diabetes          8                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
    diabetes          8       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
    diabetes          8            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]
        iris          4                       HEA (y, z)       5 [0, 1, 2, 3, 4]
        iris          4                        MPS (d=1)       5 [0, 1, 2, 3, 4]
        iris          4                        MPS (d=2)       5 [0, 1, 2, 3, 4]
        iris          4                        MPS (d=3)       5 [0, 1, 2, 3, 4]
        iris          4                       Random PQC       5 [0, 1, 2, 3, 4]
        iris          4                        TTN (d=1)       5 [0, 1, 2, 3, 4]
        iris          4                        TTN (d=2)       5 [0, 1, 2, 3, 4]
        iris          4                        TTN (d=3)       5 [0, 1, 2, 3, 4]
        iris          4              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
        iris          4 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
        iris          4    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
        iris          4   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
        iris          4           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
        iris          4                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
        iris          4       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
        iris          4            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]
        wine          4                       HEA (y, z)       5 [0, 1, 2, 3, 4]
        wine          4                        MPS (d=1)       5 [0, 1, 2, 3, 4]
        wine          4                        MPS (d=2)       5 [0, 1, 2, 3, 4]
        wine          4                        MPS (d=3)       5 [0, 1, 2, 3, 4]
        wine          4                       Random PQC       5 [0, 1, 2, 3, 4]
        wine          4                        TTN (d=1)       5 [0, 1, 2, 3, 4]
        wine          4                        TTN (d=2)       5 [0, 1, 2, 3, 4]
        wine          4                        TTN (d=3)       5 [0, 1, 2, 3, 4]
        wine          4              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
        wine          4 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
        wine          4    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
        wine          4   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
        wine          4           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
        wine          4                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
        wine          4       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
        wine          4            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]
        wine          6                       HEA (y, z)       5 [0, 1, 2, 3, 4]
        wine          6                        MPS (d=1)       5 [0, 1, 2, 3, 4]
        wine          6                        MPS (d=2)       5 [0, 1, 2, 3, 4]
        wine          6                        MPS (d=3)       5 [0, 1, 2, 3, 4]
        wine          6                       Random PQC       5 [0, 1, 2, 3, 4]
        wine          6              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
        wine          6 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
        wine          6    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
        wine          6   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
        wine          6           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
        wine          6                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
        wine          6       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
        wine          6            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]
        wine          8                       HEA (y, z)       5 [0, 1, 2, 3, 4]
        wine          8                        MPS (d=1)       5 [0, 1, 2, 3, 4]
        wine          8                        MPS (d=2)       5 [0, 1, 2, 3, 4]
        wine          8                        MPS (d=3)       5 [0, 1, 2, 3, 4]
        wine          8                       Random PQC       5 [0, 1, 2, 3, 4]
        wine          8                        TTN (d=1)       5 [0, 1, 2, 3, 4]
        wine          8                        TTN (d=2)       5 [0, 1, 2, 3, 4]
        wine          8                        TTN (d=3)       5 [0, 1, 2, 3, 4]
        wine          8              WI-PQC (E) (greedy)       5 [0, 1, 2, 3, 4]
        wine          8 WI-PQC (E) (greedy, cosine_norm)       5 [0, 1, 2, 3, 4]
        wine          8    WI-PQC (E) (greedy, top_half)       5 [0, 1, 2, 3, 4]
        wine          8   WI-PQC (E) (mwst, cosine_norm)       5 [0, 1, 2, 3, 4]
        wine          8           WI-PQC (W+E, chunking)       5 [0, 1, 2, 3, 4]
        wine          8                WI-PQC (W+E, svd)       5 [0, 1, 2, 3, 4]
        wine          8       WI-PQC (W1+W2+E, chunking)       5 [0, 1, 2, 3, 4]
        wine          8            WI-PQC (W1+W2+E, svd)       5 [0, 1, 2, 3, 4]

===== COVERAGE COUNTS BY DATASET / INPUT_DIM =====
dataset_name  input_dim  count  min  max
    diabetes          4     16    5    5
    diabetes          6     13    5    5
    diabetes          8     16    5    5
        iris          4     16    5    5
        wine          4     16    5    5
        wine          6     13    5    5
        wine          8     16    5    5

===== FULL SUMMARY =====
dataset_name  input_dim                           ansatz  n_runs  acc_mean  acc_std  prec_mean  prec_std  rec_mean  rec_std  f1_mean   f1_std  loss_mean  loss_std  time_mean   time_std
    diabetes          4                       Random PQC       5   0.47792 0.050444    0.35886  0.037375   0.65026 0.110947  0.46090 0.053070    0.80244  0.077179    4.01078   2.798080
    diabetes          4                WI-PQC (W+E, svd)       5   0.65196 0.046050    0.50174  0.084353   0.37598 0.040132  0.42858 0.053398    0.60182  0.032431   67.29220  71.999147
    diabetes          4   WI-PQC (E) (mwst, cosine_norm)       5   0.67404 0.042177    0.54428  0.085979   0.34990 0.082932  0.42378 0.080268    0.61738  0.018010   84.13322 110.679835
    diabetes          4           WI-PQC (W+E, chunking)       5   0.66232 0.049888    0.52116  0.086243   0.35758 0.092902  0.41960 0.086912    0.60522  0.031008   69.67990  77.193956
    diabetes          4              WI-PQC (E) (greedy)       5   0.66752 0.049121    0.53778  0.094164   0.34592 0.056271  0.41870 0.063513    0.59654  0.023959   41.75748  14.585944
    diabetes          4 WI-PQC (E) (greedy, cosine_norm)       5   0.65454 0.048028    0.50192  0.082262   0.34970 0.090344  0.40900 0.083915    0.60022  0.019401   53.23318  40.289403
    diabetes          4                       HEA (y, z)       5   0.64806 0.021213    0.48852  0.042146   0.34958 0.027127  0.40696 0.028623    0.63082  0.016228   32.42368   0.663428
    diabetes          4       WI-PQC (W1+W2+E, chunking)       5   0.66232 0.033422    0.52248  0.061626   0.33838 0.069392  0.40690 0.059155    0.59794  0.022335   56.58976  13.406986
    diabetes          4    WI-PQC (E) (greedy, top_half)       5   0.66754 0.025713    0.53578  0.055603   0.33054 0.079894  0.40312 0.064709    0.60810  0.027188   46.69970  28.459150
    diabetes          4            WI-PQC (W1+W2+E, svd)       5   0.62600 0.066948    0.45642  0.125483   0.34586 0.064619  0.39218 0.085952    0.61400  0.042474   50.65168   0.659674
    diabetes          4                        MPS (d=2)       5   0.58830 0.019822    0.39444  0.026370   0.35704 0.078100  0.37140 0.047092    0.65382  0.017546   23.30812   0.421496
    diabetes          4                        TTN (d=2)       5   0.58830 0.021850    0.38852  0.041344   0.34954 0.101714  0.36472 0.071181    0.65480  0.017789   22.94392   0.403536
    diabetes          4                        MPS (d=3)       5   0.58440 0.022043    0.38276  0.042809   0.34180 0.090870  0.35826 0.064858    0.65518  0.016633   33.67154   0.494945
    diabetes          4                        TTN (d=1)       5   0.58440 0.022981    0.38508  0.031696   0.33832 0.080810  0.35654 0.048966    0.65356  0.017432   14.24942   0.226875
    diabetes          4                        MPS (d=1)       5   0.57532 0.024543    0.37084  0.043290   0.34208 0.093565  0.35352 0.067987    0.65416  0.017986   14.49580   0.245200
    diabetes          4                        TTN (d=3)       5   0.57790 0.016572    0.37118  0.040739   0.33810 0.108751  0.35002 0.075164    0.65554  0.014718   33.08224   0.531141
    diabetes          6                       Random PQC       5   0.50260 0.045113    0.36362  0.036896   0.58238 0.072891  0.44684 0.043768    0.70792  0.023069   12.40690   6.559075
    diabetes          6 WI-PQC (E) (greedy, cosine_norm)       5   0.65842 0.026997    0.50910  0.049684   0.34220 0.049604  0.40830 0.047738    0.65130  0.008271  103.03920   1.343050
    diabetes          6                       HEA (y, z)       5   0.62730 0.022328    0.45422  0.034286   0.35404 0.101654  0.38894 0.073286    0.65814  0.005737   97.56992   1.669783
    diabetes          6                        MPS (d=3)       5   0.59870 0.042901    0.40982  0.063768   0.37190 0.095865  0.38632 0.077578    0.67640  0.009704  261.39910 328.116733
    diabetes          6                        MPS (d=2)       5   0.58312 0.028069    0.39136  0.038917   0.37946 0.082006  0.38294 0.058381    0.67812  0.009809   96.87974  37.495135
    diabetes          6                        MPS (d=1)       5   0.58050 0.021850    0.38878  0.035139   0.37604 0.060248  0.38112 0.042823    0.68332  0.010642   54.57186  10.379241
    diabetes          6    WI-PQC (E) (greedy, top_half)       5   0.60778 0.038032    0.40772  0.083554   0.31208 0.103194  0.35010 0.088312    0.66202  0.012125   99.72766   1.515467
    diabetes          6            WI-PQC (W1+W2+E, svd)       5   0.65454 0.011577    0.49628  0.035066   0.25968 0.086581  0.33554 0.078929    0.64604  0.007813  221.59500 168.215397
    diabetes          6   WI-PQC (E) (mwst, cosine_norm)       5   0.59610 0.039910    0.38900  0.052345   0.28946 0.089977  0.32544 0.074782    0.66020  0.012834  102.74230   2.068468
    diabetes          6                WI-PQC (W+E, svd)       5   0.64156 0.032588    0.47428  0.076484   0.24454 0.024709  0.32074 0.032084    0.64690  0.019767  234.15614 294.154567
    diabetes          6              WI-PQC (E) (greedy)       5   0.61690 0.038455    0.42268  0.064110   0.25592 0.052163  0.31412 0.044713    0.65358  0.010859  102.20072   1.172385
    diabetes          6           WI-PQC (W+E, chunking)       5   0.62206 0.037959    0.43372  0.091842   0.24822 0.057666  0.31042 0.048726    0.64830  0.016139  150.73776 107.796498
    diabetes          6       WI-PQC (W1+W2+E, chunking)       5   0.60518 0.049345    0.39986  0.098918   0.25212 0.079229  0.30344 0.076227    0.65006  0.007688  170.45134  54.065117
    diabetes          8                        MPS (d=2)       5   0.57922 0.032921    0.42094  0.030431   0.56784 0.039222  0.48270 0.025708    0.67916  0.004727  257.10354   2.693679
    diabetes          8                        TTN (d=3)       5   0.56232 0.054081    0.40252  0.053900   0.53038 0.068470  0.45600 0.050664    0.68354  0.008580  364.47368   7.800723
    diabetes          8                        TTN (d=1)       5   0.53378 0.014059    0.37682  0.014332   0.53388 0.029585  0.44154 0.016066    0.68676  0.004131  178.20638   3.643439
    diabetes          8                        MPS (d=1)       5   0.54674 0.032257    0.38442  0.028816   0.51900 0.067868  0.44082 0.039330    0.68528  0.004004  177.99098   3.113198
    diabetes          8                        MPS (d=3)       5   0.54416 0.042177    0.38274  0.041862   0.51912 0.057585  0.44040 0.047250    0.68428  0.010176  365.46902   4.479734
    diabetes          8                        TTN (d=2)       5   0.55324 0.039864    0.38794  0.041986   0.50788 0.061288  0.43972 0.049086    0.68536  0.008043  257.37268   3.328273
    diabetes          8                       Random PQC       5   0.49222 0.044145    0.33938  0.028569   0.48882 0.031422  0.39996 0.024862    0.69456  0.003561   31.14880  18.712341
    diabetes          8    WI-PQC (E) (greedy, top_half)       5   0.57662 0.036272    0.37656  0.062415   0.37178 0.162586  0.36464 0.103027    0.67948  0.013465  297.42152   3.410435
    diabetes          8           WI-PQC (W+E, chunking)       5   0.59610 0.034517    0.40458  0.037712   0.33076 0.064205  0.35876 0.037446    0.67662  0.008893  302.06284   1.849813
    diabetes          8                       HEA (y, z)       5   0.62210 0.024059    0.43212  0.043180   0.29336 0.029941  0.34908 0.032971    0.65702  0.010642  294.57050   3.081971
    diabetes          8 WI-PQC (E) (greedy, cosine_norm)       5   0.62598 0.045380    0.44602  0.070317   0.28574 0.080625  0.34174 0.064946    0.66192  0.014231  303.32772   3.228060
    diabetes          8              WI-PQC (E) (greedy)       5   0.63118 0.050185    0.45670  0.139828   0.25200 0.127225  0.30554 0.126177    0.66028  0.009100  303.79206   3.669907
    diabetes          8       WI-PQC (W1+W2+E, chunking)       5   0.60390 0.059688    0.39020  0.109306   0.25946 0.117535  0.30388 0.114705    0.66364  0.012076  431.29610   9.026436
    diabetes          8                WI-PQC (W+E, svd)       5   0.62726 0.043949    0.43760  0.077213   0.24424 0.115145  0.29740 0.113963    0.66544  0.008415  302.08824   1.569633
    diabetes          8            WI-PQC (W1+W2+E, svd)       5   0.60782 0.041731    0.39714  0.074643   0.23300 0.065679  0.28798 0.058875    0.66812  0.009441  430.84154   6.912288
    diabetes          8   WI-PQC (E) (mwst, cosine_norm)       5   0.61300 0.038619    0.37768  0.114477   0.19950 0.077889  0.26012 0.091811    0.66746  0.010411  302.39942   2.943091
        iris          4            WI-PQC (W1+W2+E, svd)       5   0.63334 0.040825    0.64134  0.036594   0.63334 0.040825  0.62900 0.037750    0.93464  0.080559    9.75578   0.179841
        iris          4                WI-PQC (W+E, svd)       5   0.62668 0.109060    0.65302  0.099911   0.62668 0.109060  0.61978 0.111508    0.91284  0.076781    6.78038   0.139166
        iris          4           WI-PQC (W+E, chunking)       5   0.62668 0.121098    0.63452  0.135905   0.62668 0.121098  0.61876 0.117497    0.91390  0.077155    6.79310   0.142992
        iris          4                       HEA (y, z)       5   0.60666 0.095427    0.64366  0.117996   0.60666 0.095427  0.59914 0.102849    0.91880  0.091529    6.23444   0.171153
        iris          4       WI-PQC (W1+W2+E, chunking)       5   0.60666 0.103833    0.61814  0.131757   0.60666 0.103833  0.58830 0.117390    0.90634  0.039317    9.79718   0.256920
        iris          4    WI-PQC (E) (greedy, top_half)       5   0.58666 0.044706    0.60758  0.076227   0.58666 0.044706  0.57832 0.039348    0.93720  0.043044    6.55890   0.131650
        iris          4 WI-PQC (E) (greedy, cosine_norm)       5   0.59336 0.129957    0.59728  0.162387   0.59336 0.129957  0.57044 0.122832    0.96156  0.093210    6.82098   0.199453

In [16]:
print(summary5.to_string(index=False))
print(topk.to_string(index=False))
print(coverage.groupby(["dataset_name", "input_dim"])["n_runs"].agg(["count", "min", "max"]).reset_index().to_string(index=False))

dataset_name  input_dim                           ansatz  n_runs  acc_mean  acc_std  prec_mean  prec_std  rec_mean  rec_std  f1_mean   f1_std  loss_mean  loss_std  time_mean   time_std
    diabetes          4                       Random PQC       5   0.47792 0.050444    0.35886  0.037375   0.65026 0.110947  0.46090 0.053070    0.80244  0.077179    4.01078   2.798080
    diabetes          4                WI-PQC (W+E, svd)       5   0.65196 0.046050    0.50174  0.084353   0.37598 0.040132  0.42858 0.053398    0.60182  0.032431   67.29220  71.999147
    diabetes          4   WI-PQC (E) (mwst, cosine_norm)       5   0.67404 0.042177    0.54428  0.085979   0.34990 0.082932  0.42378 0.080268    0.61738  0.018010   84.13322 110.679835
    diabetes          4           WI-PQC (W+E, chunking)       5   0.66232 0.049888    0.52116  0.086243   0.35758 0.092902  0.41960 0.086912    0.60522  0.031008   69.67990  77.193956
    diabetes          4              WI-PQC (E) (greedy)       5   0.66752 0.049121    0.53778  0.094164   0.34592 0.056271  0.41870 0.063513    0.59654  0.023959   41.75748  14.585944
    diabetes          4 WI-PQC (E) (greedy, cosine_norm)       5   0.65454 0.048028    0.50192  0.082262   0.34970 0.090344  0.40900 0.083915    0.60022  0.019401   53.23318  40.289403
    diabetes          4                       HEA (y, z)       5   0.64806 0.021213    0.48852  0.042146   0.34958 0.027127  0.40696 0.028623    0.63082  0.016228   32.42368   0.663428
    diabetes          4       WI-PQC (W1+W2+E, chunking)       5   0.66232 0.033422    0.52248  0.061626   0.33838 0.069392  0.40690 0.059155    0.59794  0.022335   56.58976  13.406986
    diabetes          4    WI-PQC (E) (greedy, top_half)       5   0.66754 0.025713    0.53578  0.055603   0.33054 0.079894  0.40312 0.064709    0.60810  0.027188   46.69970  28.459150
    diabetes          4            WI-PQC (W1+W2+E, svd)       5   0.62600 0.066948    0.45642  0.125483   0.34586 0.064619  0.39218 0.085952    0.61400  0.042474   50.65168   0.659674
    diabetes          4                        MPS (d=2)       5   0.58830 0.019822    0.39444  0.026370   0.35704 0.078100  0.37140 0.047092    0.65382  0.017546   23.30812   0.421496
    diabetes          4                        TTN (d=2)       5   0.58830 0.021850    0.38852  0.041344   0.34954 0.101714  0.36472 0.071181    0.65480  0.017789   22.94392   0.403536
    diabetes          4                        MPS (d=3)       5   0.58440 0.022043    0.38276  0.042809   0.34180 0.090870  0.35826 0.064858    0.65518  0.016633   33.67154   0.494945
    diabetes          4                        TTN (d=1)       5   0.58440 0.022981    0.38508  0.031696   0.33832 0.080810  0.35654 0.048966    0.65356  0.017432   14.24942   0.226875
    diabetes          4                        MPS (d=1)       5   0.57532 0.024543    0.37084  0.043290   0.34208 0.093565  0.35352 0.067987    0.65416  0.017986   14.49580   0.245200
    diabetes          4                        TTN (d=3)       5   0.57790 0.016572    0.37118  0.040739   0.33810 0.108751  0.35002 0.075164    0.65554  0.014718   33.08224   0.531141
    diabetes          6                       Random PQC       5   0.50260 0.045113    0.36362  0.036896   0.58238 0.072891  0.44684 0.043768    0.70792  0.023069   12.40690   6.559075
    diabetes          6 WI-PQC (E) (greedy, cosine_norm)       5   0.65842 0.026997    0.50910  0.049684   0.34220 0.049604  0.40830 0.047738    0.65130  0.008271  103.03920   1.343050
    diabetes          6                       HEA (y, z)       5   0.62730 0.022328    0.45422  0.034286   0.35404 0.101654  0.38894 0.073286    0.65814  0.005737   97.56992   1.669783
    diabetes          6                        MPS (d=3)       5   0.59870 0.042901    0.40982  0.063768   0.37190 0.095865  0.38632 0.077578    0.67640  0.009704  261.39910 328.116733
    diabetes          6                        MPS (d=2)       5   0.58312 0.028069    0.39136  0.038917   0.37946 0.082006  0.38294 0.058381    0.67812  0.009809   96.87974  37.495135
    diabetes          6                        MPS (d=1)       5   0.58050 0.021850    0.38878  0.035139   0.37604 0.060248  0.38112 0.042823    0.68332  0.010642   54.57186  10.379241
    diabetes          6    WI-PQC (E) (greedy, top_half)       5   0.60778 0.038032    0.40772  0.083554   0.31208 0.103194  0.35010 0.088312    0.66202  0.012125   99.72766   1.515467
    diabetes          6            WI-PQC (W1+W2+E, svd)       5   0.65454 0.011577    0.49628  0.035066   0.25968 0.086581  0.33554 0.078929    0.64604  0.007813  221.59500 168.215397
    diabetes          6   WI-PQC (E) (mwst, cosine_norm)       5   0.59610 0.039910    0.38900  0.052345   0.28946 0.089977  0.32544 0.074782    0.66020  0.012834  102.74230   2.068468
    diabetes          6                WI-PQC (W+E, svd)       5   0.64156 0.032588    0.47428  0.076484   0.24454 0.024709  0.32074 0.032084    0.64690  0.019767  234.15614 294.154567
    diabetes          6              WI-PQC (E) (greedy)       5   0.61690 0.038455    0.42268  0.064110   0.25592 0.052163  0.31412 0.044713    0.65358  0.010859  102.20072   1.172385
    diabetes          6           WI-PQC (W+E, chunking)       5   0.62206 0.037959    0.43372  0.091842   0.24822 0.057666  0.31042 0.048726    0.64830  0.016139  150.73776 107.796498
    diabetes          6       WI-PQC (W1+W2+E, chunking)       5   0.60518 0.049345    0.39986  0.098918   0.25212 0.079229  0.30344 0.076227    0.65006  0.007688  170.45134  54.065117
    diabetes          8                        MPS (d=2)       5   0.57922 0.032921    0.42094  0.030431   0.56784 0.039222  0.48270 0.025708    0.67916  0.004727  257.10354   2.693679
    diabetes          8                        TTN (d=3)       5   0.56232 0.054081    0.40252  0.053900   0.53038 0.068470  0.45600 0.050664    0.68354  0.008580  364.47368   7.800723
    diabetes          8                        TTN (d=1)       5   0.53378 0.014059    0.37682  0.014332   0.53388 0.029585  0.44154 0.016066    0.68676  0.004131  178.20638   3.643439
    diabetes          8                        MPS (d=1)       5   0.54674 0.032257    0.38442  0.028816   0.51900 0.067868  0.44082 0.039330    0.68528  0.004004  177.99098   3.113198
    diabetes          8                        MPS (d=3)       5   0.54416 0.042177    0.38274  0.041862   0.51912 0.057585  0.44040 0.047250    0.68428  0.010176  365.46902   4.479734
    diabetes          8                        TTN (d=2)       5   0.55324 0.039864    0.38794  0.041986   0.50788 0.061288  0.43972 0.049086    0.68536  0.008043  257.37268   3.328273
    diabetes          8                       Random PQC       5   0.49222 0.044145    0.33938  0.028569   0.48882 0.031422  0.39996 0.024862    0.69456  0.003561   31.14880  18.712341
    diabetes          8    WI-PQC (E) (greedy, top_half)       5   0.57662 0.036272    0.37656  0.062415   0.37178 0.162586  0.36464 0.103027    0.67948  0.013465  297.42152   3.410435
    diabetes          8           WI-PQC (W+E, chunking)       5   0.59610 0.034517    0.40458  0.037712   0.33076 0.064205  0.35876 0.037446    0.67662  0.008893  302.06284   1.849813
    diabetes          8                       HEA (y, z)       5   0.62210 0.024059    0.43212  0.043180   0.29336 0.029941  0.34908 0.032971    0.65702  0.010642  294.57050   3.081971
    diabetes          8 WI-PQC (E) (greedy, cosine_norm)       5   0.62598 0.045380    0.44602  0.070317   0.28574 0.080625  0.34174 0.064946    0.66192  0.014231  303.32772   3.228060
    diabetes          8              WI-PQC (E) (greedy)       5   0.63118 0.050185    0.45670  0.139828   0.25200 0.127225  0.30554 0.126177    0.66028  0.009100  303.79206   3.669907
    diabetes          8       WI-PQC (W1+W2+E, chunking)       5   0.60390 0.059688    0.39020  0.109306   0.25946 0.117535  0.30388 0.114705    0.66364  0.012076  431.29610   9.026436
    diabetes          8                WI-PQC (W+E, svd)       5   0.62726 0.043949    0.43760  0.077213   0.24424 0.115145  0.29740 0.113963    0.66544  0.008415  302.08824   1.569633
    diabetes          8            WI-PQC (W1+W2+E, svd)       5   0.60782 0.041731    0.39714  0.074643   0.23300 0.065679  0.28798 0.058875    0.66812  0.009441  430.84154   6.912288
    diabetes          8   WI-PQC (E) (mwst, cosine_norm)       5   0.61300 0.038619    0.37768  0.114477   0.19950 0.077889  0.26012 0.091811    0.66746  0.010411  302.39942   2.943091
        iris          4            WI-PQC (W1+W2+E, svd)       5   0.63334 0.040825    0.64134  0.036594   0.63334 0.040825  0.62900 0.037750    0.93464  0.080559    9.75578   0.179841
        iris          4                WI-PQC (W+E, svd)       5   0.62668 0.109060    0.65302  0.099911   0.62668 0.109060  0.61978 0.111508    0.91284  0.076781    6.78038   0.139166
        iris          4           WI-PQC (W+E, chunking)       5   0.62668 0.121098    0.63452  0.135905   0.62668 0.121098  0.61876 0.117497    0.91390  0.077155    6.79310   0.142992
        iris          4                       HEA (y, z)       5   0.60666 0.095427    0.64366  0.117996   0.60666 0.095427  0.59914 0.102849    0.91880  0.091529    6.23444   0.171153
        iris          4       WI-PQC (W1+W2+E, chunking)       5   0.60666 0.103833    0.61814  0.131757   0.60666 0.103833  0.58830 0.117390    0.90634  0.039317    9.79718   0.256920
        iris          4    WI-PQC (E) (greedy, top_half)       5   0.58666 0.044706    0.60758  0.076227   0.58666 0.044706  0.57832 0.039348    0.93720  0.043044    6.55890   0.131650
        iris          4 WI-PQC (E) (greedy, cosine_norm)       5   0.59336 0.129957    0.59728  0.162387   0.59336 0.129957  0.57044 0.122832    0.96156  0.093210    6.82098   0.199453
        iris          4   WI-PQC (E) (mwst, cosine_norm)       5   0.58000 0.096018    0.59468  0.094482   0.58000 0.096018  0.56682 0.094091    0.94862  0.095815    6.62870   0.097860
        iris          4              WI-PQC (E) (greedy)       5   0.57998 0.148326    0.57654  0.156689   0.57998 0.148326  0.56152 0.153835    0.94842  0.106620    6.86748   0.262526
        iris          4                        MPS (d=3)       5   0.55332 0.086949    0.56086  0.085190   0.55332 0.086949  0.54958 0.088644    0.98370  0.037820    6.51786   0.142699
        iris          4                        TTN (d=3)       5   0.51330 0.083666    0.52166  0.074481   0.51330 0.083666  0.50098 0.093852    1.01478  0.088514    6.49108   0.218100
        iris          4                        MPS (d=1)       5   0.50002 0.047129    0.51732  0.067189   0.50002 0.047129  0.49204 0.055967    1.01156  0.048008    2.81778   0.090950
        iris          4                        TTN (d=2)       5   0.51334 0.121570    0.50290  0.125674   0.51334 0.121570  0.49156 0.120828    0.98586  0.069522    4.41846   0.064204
        iris          4                        MPS (d=2)       5   0.48666 0.093106    0.49702  0.122987   0.48666 0.093106  0.48156 0.099334    0.98374  0.072804    4.54964   0.167135
        iris          4                        TTN (d=1)       5   0.43334 0.158103    0.44472  0.169357   0.43334 0.158103  0.42664 0.156270    1.04582  0.055331    2.75048   0.041160
        iris          4                       Random PQC       5   0.33998 0.106460    0.33450  0.119915   0.33998 0.106460  0.32286 0.109140    1.11392  0.097510    0.76864   0.538713
        wine          4              WI-PQC (E) (greedy)       5   0.65000 0.112160    0.66418  0.081599   0.64662 0.108712  0.64864 0.104109    0.89260  0.076966    8.21594   0.216589
        wine          4            WI-PQC (W1+W2+E, svd)       5   0.65554 0.050449    0.66226  0.062763   0.64858 0.059020  0.64108 0.057920    0.86808  0.030387   11.73034   0.158901
        wine          4                WI-PQC (W+E, svd)       5   0.62778 0.112170    0.65140  0.104548   0.62334 0.116296  0.61922 0.104765    0.90204  0.067017    8.21374   0.230304
        wine          4 WI-PQC (E) (greedy, cosine_norm)       5   0.61668 0.049699    0.62756  0.047374   0.60924 0.052920  0.60864 0.047548    0.88618  0.048700    8.24002   0.266387
        wine          4           WI-PQC (W+E, chunking)       5   0.61670 0.056919    0.62612  0.048522   0.61382 0.051708  0.60520 0.047674    0.91480  0.056354    8.23378   0.259552
        wine          4   WI-PQC (E) (mwst, cosine_norm)       5   0.61666 0.099001    0.62734  0.150513   0.60594 0.110276  0.60404 0.117068    0.90734  0.048921    8.08000   0.223569
        wine          4       WI-PQC (W1+W2+E, chunking)       5   0.61110 0.070808    0.60000  0.083689   0.60464 0.091593  0.59760 0.088842    0.88284  0.067024   11.79306   0.273240
        wine          4                       HEA (y, z)       5   0.58332 0.102062    0.58726  0.082594   0.58762 0.090800  0.57754 0.091209    0.92942  0.098809    7.47378   0.155204
        wine          4    WI-PQC (E) (greedy, top_half)       5   0.59442 0.089150    0.59856  0.119898   0.58312 0.080797  0.57398 0.089116    0.96720  0.098423    7.89860   0.195795
        wine          4                        TTN (d=2)       5   0.56668 0.050457    0.57684  0.062124   0.56874 0.038104  0.55888 0.052660    0.97184  0.042605    5.35108   0.082672
        wine          4                        MPS (d=2)       5   0.52780 0.105761    0.54348  0.124032   0.52436 0.109951  0.51918 0.113310    0.97214  0.065190    5.39660   0.083588
        wine          4                        MPS (d=3)       5   0.51110 0.138334    0.52366  0.151952   0.51122 0.135787  0.48880 0.118760    1.00022  0.067824    7.77862   0.122364
        wine          4                        TTN (d=3)       5   0.49444 0.079546    0.49834  0.066053   0.49302 0.066864  0.48120 0.077439    1.00042  0.063576    7.70968   0.123448
        wine          4                        TTN (d=1)       5   0.44444 0.087824    0.46088  0.087479   0.45380 0.088349  0.43680 0.086435    1.03822  0.023443    3.31854   0.049907
        wine          4                        MPS (d=1)       5   0.41666 0.112813    0.43088  0.110987   0.42096 0.108193  0.41814 0.112449    1.06462  0.052808    3.35204   0.052097
        wine          4                       Random PQC       5   0.42222 0.135206    0.47142  0.136960   0.43710 0.123503  0.39602 0.126788    1.10012  0.117664    0.93100   0.653123
        wine          6       WI-PQC (W1+W2+E, chunking)       5   0.48334 0.042121    0.48640  0.043258   0.50826 0.045591  0.47838 0.043588    1.05610  0.025037   75.17996  92.698299
        wine          6 WI-PQC (E) (greedy, cosine_norm)       5   0.47776 0.071891    0.47336  0.063057   0.47264 0.060617  0.46284 0.053890    1.04382  0.012073   51.02272  46.123244
        wine          6            WI-PQC (W1+W2+E, svd)       5   0.46112 0.057609    0.46360  0.064718   0.48672 0.067311  0.45704 0.049714    1.05320  0.019946   51.56586  39.984464
        wine          6                WI-PQC (W+E, svd)       5   0.46666 0.030412    0.45902  0.024102   0.48254 0.040543  0.45654 0.031575    1.05892  0.042766  125.87120 192.050524
        wine          6                        MPS (d=3)       5   0.46666 0.102818    0.46098  0.107281   0.46672 0.103113  0.45316 0.097163    1.04324  0.033730   26.63418   0.362673
        wine          6   WI-PQC (E) (mwst, cosine_norm)       5   0.46666 0.045653    0.43084  0.046481   0.48366 0.031051  0.43826 0.032185    1.04948  0.019616   61.36476  84.626954
        wine          6           WI-PQC (W+E, chunking)       5   0.43888 0.036197    0.42724  0.039198   0.45000 0.059937  0.42082 0.044119    1.04494  0.029387   56.98718  74.404820
        wine          6                        MPS (d=2)       5   0.42780 0.126680    0.42662  0.137974   0.42918 0.141967  0.41388 0.136717    1.07794  0.039606   18.50648   0.290797
        wine          6                        MPS (d=1)       5   0.42222 0.098983    0.43566  0.101225   0.42200 0.095086  0.40586 0.098743    1.06330  0.045211   11.61764   0.269225
        wine          6              WI-PQC (E) (greedy)       5   0.41666 0.112813    0.40906  0.144776   0.42528 0.112098  0.40242 0.122466    1.06120  0.040883   23.63848   0.381318
        wine          6    WI-PQC (E) (greedy, top_half)       5   0.40002 0.095431    0.40340  0.103347   0.41496 0.104142  0.39856 0.107514    1.08020  0.038627   57.42382  76.960659
        wine          6                       HEA (y, z)       5   0.41666 0.034007    0.44024  0.075898   0.42864 0.016267  0.39600 0.038732    1.06854  0.024699   22.30174   0.315805
        wine          6                       Random PQC       5   0.36668 0.088706    0.37442  0.137350   0.36350 0.094651  0.33754 0.086296    1.12042  0.031986    8.56034  14.171905
        wine          8       WI-PQC (W1+W2+E, chunking)       5   0.44444 0.134678    0.42708  0.159262   0.43604 0.144315  0.42356 0.153901    1.07496  0.020585  102.52948   2.982601
        wine          8   WI-PQC (E) (mwst, cosine_norm)       5   0.43332 0.075026    0.42938  0.098874   0.43094 0.082800  0.42080 0.085406    1.08128  0.011388   71.03902   1.100715
        wine          8                        MPS (d=3)       5   0.42778 0.031649    0.41942  0.041808   0.42234 0.042113  0.41636 0.038608    1.08560  0.018868   86.34156   2.769264
        wine          8                        TTN (d=2)       5   0.41666 0.103938    0.40830  0.116789   0.42328 0.105227  0.40746 0.113021    1.07732  0.014281   59.71850   0.913515
        wine          8              WI-PQC (E) (greedy)       5   0.41114 0.012433    0.39404  0.014906   0.40424 0.019382  0.39666 0.015809    1.08404  0.007642   71.18164   0.948925
        wine          8            WI-PQC (W1+W2+E, svd)       5   0.40556 0.063963    0.39700  0.070518   0.40112 0.052494  0.39228 0.064169    1.08620  0.007285  101.14654   1.637293
        wine          8                       HEA (y, z)       5   0.40554 0.151627    0.39722  0.147138   0.39406 0.159489  0.39030 0.154007    1.07966  0.037763   69.54236   0.942853
        wine          8                        TTN (d=1)       5   0.41110 0.071906    0.39810  0.077254   0.40090 0.074684  0.38714 0.070225    1.08616  0.016672   41.54822   1.077574
        wine          8    WI-PQC (E) (greedy, top_half)       5   0.40002 0.108670    0.39128  0.114093   0.39460 0.110292  0.38520 0.113221    1.07826  0.026806   69.88516   0.866484
        wine          8                        MPS (d=2)       5   0.40000 0.054159    0.39374  0.058538   0.38742 0.055984  0.38378 0.054064    1.07706  0.017113   60.24788   0.994826
        wine          8           WI-PQC (W+E, chunking)       5   0.38334 0.100906    0.38436  0.089939   0.38304 0.095385  0.37884 0.092943    1.08976  0.020590   71.31362   0.935786
        wine          8                        TTN (d=3)       5   0.38888 0.081007    0.39402  0.103213   0.38316 0.082828  0.37650 0.089035    1.08582  0.015028   84.97722   2.138284
        wine          8                WI-PQC (W+E, svd)       5   0.36666 0.071891    0.35174  0.095743   0.36800 0.085554  0.34358 0.077120    1.08394  0.013224   71.23310   1.042117
        wine          8                        MPS (d=1)       5   0.35000 0.063961    0.35866  0.068738   0.34524 0.050798  0.34168 0.061741    1.09446  0.022786   41.82780   0.949015
        wine          8                       Random PQC       5   0.32224 0.054143    0.32672  0.058673   0.32392 0.070563  0.31518 0.059059    1.09894  0.003404    7.43170   4.399079
        wine          8 WI-PQC (E) (greedy, cosine_norm)       5   0.31112 0.049680    0.28752  0.081970   0.30772 0.055917  0.29240 0.071781    1.09244  0.012966   71.34968   0.997070
dataset_name  input_dim                           ansatz  n_runs  acc_mean  acc_std  prec_mean  prec_std  rec_mean  rec_std  f1_mean   f1_std  loss_mean  loss_std  time_mean   time_std

In [17]:
import pandas as pd
from pathlib import Path

# ============================================================
# LOAD THE MERGED 5-SEED SUMMARY
# ============================================================

summary5_fp = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/summary_5seed.csv")
summary5 = pd.read_csv(summary5_fp)

# ------------------------------------------------------------
# Helper predicates
# ------------------------------------------------------------

def is_wi(ansatz: str) -> bool:
    return isinstance(ansatz, str) and ansatz.startswith("WI-PQC")

def is_tn(ansatz: str) -> bool:
    return isinstance(ansatz, str) and (ansatz.startswith("MPS") or ansatz.startswith("TTN"))

def is_hea(ansatz: str) -> bool:
    return ansatz == "HEA (y, z)"

def is_random(ansatz: str) -> bool:
    return ansatz == "Random PQC"

# ------------------------------------------------------------
# Selectors
# ------------------------------------------------------------

def best_row(df: pd.DataFrame, mask_fn):
    sub = df[df["ansatz"].apply(mask_fn)].copy()
    if sub.empty:
        return None
    sub = sub.sort_values(
        ["f1_mean", "loss_mean", "acc_mean"],
        ascending=[False, True, False]
    )
    return sub.iloc[0]

def top_two_wi(df: pd.DataFrame):
    sub = df[df["ansatz"].apply(is_wi)].copy()
    if sub.empty:
        return []
    sub = sub.sort_values(
        ["f1_mean", "loss_mean", "acc_mean"],
        ascending=[False, True, False]
    )
    return [row for _, row in sub.head(2).iterrows()]

# ============================================================
# BUILD CROSS-QUBIT SUMMARY TABLE CONTENT
# ============================================================

rows_cross = []

for (dataset, input_dim), g in summary5.groupby(["dataset_name", "input_dim"], sort=True):
    hea = best_row(g, is_hea)
    wi = best_row(g, is_wi)
    tn = best_row(g, is_tn)
    rnd = best_row(g, is_random)

    rows_cross.append({
        "dataset": dataset,
        "q": int(input_dim),
        "HEA_f1": hea["f1_mean"] if hea is not None else None,
        "HEA_loss": hea["loss_mean"] if hea is not None else None,
        "best_wi_name": wi["ansatz"] if wi is not None else None,
        "best_wi_f1": wi["f1_mean"] if wi is not None else None,
        "best_wi_loss": wi["loss_mean"] if wi is not None else None,
        "best_tn_name": tn["ansatz"] if tn is not None else None,
        "best_tn_f1": tn["f1_mean"] if tn is not None else None,
        "best_tn_loss": tn["loss_mean"] if tn is not None else None,
        "random_f1": rnd["f1_mean"] if rnd is not None else None,
        "random_loss": rnd["loss_mean"] if rnd is not None else None,
    })

cross_df = pd.DataFrame(rows_cross).sort_values(["dataset", "q"])

print("===== CROSS-QUBIT SUMMARY SELECTIONS =====")
print(cross_df.to_string(index=False))
print()

# ============================================================
# BUILD WI-PQC ABLATION TABLE CONTENT
# ============================================================

rows_ablation = []

for (dataset, input_dim), g in summary5.groupby(["dataset_name", "input_dim"], sort=True):
    best_two = top_two_wi(g)
    if len(best_two) == 0:
        continue

    best1 = best_two[0]
    best2 = best_two[1] if len(best_two) > 1 else None

    rows_ablation.append({
        "dataset": dataset,
        "q": int(input_dim),
        "best_wi": best1["ansatz"],
        "best_wi_f1": best1["f1_mean"],
        "best_wi_loss": best1["loss_mean"],
        "runner_up_wi": best2["ansatz"] if best2 is not None else None,
        "runner_up_wi_f1": best2["f1_mean"] if best2 is not None else None,
    })

ablation_df = pd.DataFrame(rows_ablation).sort_values(["dataset", "q"])

print("===== WI-PQC ABLATION SELECTIONS =====")
print(ablation_df.to_string(index=False))
print()

# ============================================================
# LATEX HELPERS
# ============================================================

def fmt_pair(f1, loss):
    if pd.isna(f1) or pd.isna(loss):
        return "---"
    return f"{f1:.3f} ({loss:.3f})"

def latex_escape(s: str) -> str:
    if s is None or pd.isna(s):
        return "---"
    s = s.replace("W1+W2", "W$_1$W$_2$")
    return s

# ------------------------------------------------------------
# Generate Table 1 rows
# ------------------------------------------------------------

print("===== LATEX ROWS: TABLE 1 (CROSS-QUBIT SUMMARY) =====")
for _, r in cross_df.iterrows():
    line = (
        f'{r["dataset"].capitalize()} & {int(r["q"])} '
        f'& {fmt_pair(r["HEA_f1"], r["HEA_loss"])} '
        f'& {latex_escape(r["best_wi_name"])}: {fmt_pair(r["best_wi_f1"], r["best_wi_loss"])} '
        f'& {latex_escape(r["best_tn_name"])}: {fmt_pair(r["best_tn_f1"], r["best_tn_loss"])} '
        f'& {fmt_pair(r["random_f1"], r["random_loss"])} \\\\'
    )
    print(line)
print()

# ------------------------------------------------------------
# Generate Table 2 rows
# ------------------------------------------------------------

print("===== LATEX ROWS: TABLE 2 (WI-PQC ABLATION) =====")
for _, r in ablation_df.iterrows():
    best = f'{latex_escape(r["best_wi"])} & {r["best_wi_f1"]:.3f} & {r["best_wi_loss"]:.3f}'
    if pd.isna(r["runner_up_wi_f1"]):
        runner = "--- & ---"
    else:
        runner = f'{latex_escape(r["runner_up_wi"])} & {r["runner_up_wi_f1"]:.3f}'
    line = f'{r["dataset"].capitalize()} & {int(r["q"])} & {best} & {runner} \\\\'
    print(line)
print()

# ============================================================
# OPTIONAL: SAVE THE SELECTION TABLES
# ============================================================

out_dir = summary5_fp.parent
cross_df.to_csv(out_dir / "table1_cross_qubit_summary_content.csv", index=False)
ablation_df.to_csv(out_dir / "table2_wipqc_ablation_content.csv", index=False)

print("Saved:")
print(" ", out_dir / "table1_cross_qubit_summary_content.csv")
print(" ", out_dir / "table2_wipqc_ablation_content.csv")

===== CROSS-QUBIT SUMMARY SELECTIONS =====
 dataset  q  HEA_f1  HEA_loss                     best_wi_name  best_wi_f1  best_wi_loss best_tn_name  best_tn_f1  best_tn_loss  random_f1  random_loss
diabetes  4 0.40696   0.63082                WI-PQC (W+E, svd)     0.42858       0.60182    MPS (d=2)     0.37140       0.65382    0.46090      0.80244
diabetes  6 0.38894   0.65814 WI-PQC (E) (greedy, cosine_norm)     0.40830       0.65130    MPS (d=3)     0.38632       0.67640    0.44684      0.70792
diabetes  8 0.34908   0.65702    WI-PQC (E) (greedy, top_half)     0.36464       0.67948    MPS (d=2)     0.48270       0.67916    0.39996      0.69456
    iris  4 0.59914   0.91880            WI-PQC (W1+W2+E, svd)     0.62900       0.93464    MPS (d=3)     0.54958       0.98370    0.32286      1.11392
    wine  4 0.57754   0.92942              WI-PQC (E) (greedy)     0.64864       0.89260    TTN (d=2)     0.55888       0.97184    0.39602      1.10012
    wine  6 0.39600   1.06854       WI-PQC (W1+W2+E, chunking)     0.47838       1.05610    MPS (d=3)     0.45316       1.04324    0.33754      1.12042
    wine  8 0.39030   1.07966       WI-PQC (W1+W2+E, chunking)     0.42356       1.07496    MPS (d=3)     0.41636       1.08560    0.31518      1.09894

===== WI-PQC ABLATION SELECTIONS =====
 dataset  q                          best_wi  best_wi_f1  best_wi_loss                     runner_up_wi  runner_up_wi_f1
diabetes  4                WI-PQC (W+E, svd)     0.42858       0.60182   WI-PQC (E) (mwst, cosine_norm)          0.42378
diabetes  6 WI-PQC (E) (greedy, cosine_norm)     0.40830       0.65130    WI-PQC (E) (greedy, top_half)          0.35010
diabetes  8    WI-PQC (E) (greedy, top_half)     0.36464       0.67948           WI-PQC (W+E, chunking)          0.35876
    iris  4            WI-PQC (W1+W2+E, svd)     0.62900       0.93464                WI-PQC (W+E, svd)          0.61978
    wine  4              WI-PQC (E) (greedy)     0.64864       0.89260            WI-PQC (W1+W2+E, svd)          0.64108
    wine  6       WI-PQC (W1+W2+E, chunking)     0.47838       1.05610 WI-PQC (E) (greedy, cosine_norm)          0.46284
    wine  8       WI-PQC (W1+W2+E, chunking)     0.42356       1.07496   WI-PQC (E) (mwst, cosine_norm)          0.42080

===== LATEX ROWS: TABLE 1 (CROSS-QUBIT SUMMARY) =====
Diabetes & 4 & 0.407 (0.631) & WI-PQC (W+E, svd): 0.429 (0.602) & MPS (d=2): 0.371 (0.654) & 0.461 (0.802) \\
Diabetes & 6 & 0.389 (0.658) & WI-PQC (E) (greedy, cosine_norm): 0.408 (0.651) & MPS (d=3): 0.386 (0.676) & 0.447 (0.708) \\
Diabetes & 8 & 0.349 (0.657) & WI-PQC (E) (greedy, top_half): 0.365 (0.679) & MPS (d=2): 0.483 (0.679) & 0.400 (0.695) \\
Iris & 4 & 0.599 (0.919) & WI-PQC (W$_1$W$_2$+E, svd): 0.629 (0.935) & MPS (d=3): 0.550 (0.984) & 0.323 (1.114) \\
Wine & 4 & 0.578 (0.929) & WI-PQC (E) (greedy): 0.649 (0.893) & TTN (d=2): 0.559 (0.972) & 0.396 (1.100) \\
Wine & 6 & 0.396 (1.069) & WI-PQC (W$_1$W$_2$+E, chunking): 0.478 (1.056) & MPS (d=3): 0.453 (1.043) & 0.338 (1.120) \\
Wine & 8 & 0.390 (1.080) & WI-PQC (W$_1$W$_2$+E, chunking): 0.424 (1.075) & MPS (d=3): 0.416 (1.086) & 0.315 (1.099) \\

===== LATEX ROWS: TABLE 2 (WI-PQC ABLATION) =====
Diabetes & 4 & WI-PQC (W+E, svd) & 0.429 & 0.602 & WI-PQC (E) (mwst, cosine_norm) & 0.424 \\
Diabetes & 6 & WI-PQC (E) (greedy, cosine_norm) & 0.408 & 0.651 & WI-PQC (E) (greedy, top_half) & 0.350 \\
Diabetes & 8 & WI-PQC (E) (greedy, top_half) & 0.365 & 0.679 & WI-PQC (W+E, chunking) & 0.359 \\
Iris & 4 & WI-PQC (W$_1$W$_2$+E, svd) & 0.629 & 0.935 & WI-PQC (W+E, svd) & 0.620 \\
Wine & 4 & WI-PQC (E) (greedy) & 0.649 & 0.893 & WI-PQC (W$_1$W$_2$+E, svd) & 0.641 \\
Wine & 6 & WI-PQC (W$_1$W$_2$+E, chunking) & 0.478 & 1.056 & WI-PQC (E) (greedy, cosine_norm) & 0.463 \\
Wine & 8 & WI-PQC (W$_1$W$_2$+E, chunking) & 0.424 & 1.075 & WI-PQC (E) (mwst, cosine_norm) & 0.421 \\

Saved:
  /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/table1_cross_qubit_summary_content.csv
  /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/table2_wipqc_ablation_content.csv

In [ ]:
import pandas as pd
from pathlib import Path

# ============================================================
# LOAD SUMMARY
# ============================================================

summary5_fp = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/summary_5seed.csv")
summary5 = pd.read_csv(summary5_fp)

# ============================================================
# HELPERS
# ============================================================

def is_wi(ansatz: str) -> bool:
    return isinstance(ansatz, str) and ansatz.startswith("WI-PQC")

def is_mps(ansatz: str) -> bool:
    return isinstance(ansatz, str) and ansatz.startswith("MPS")

def is_ttn(ansatz: str) -> bool:
    return isinstance(ansatz, str) and ansatz.startswith("TTN")

def is_hea(ansatz: str) -> bool:
    return ansatz == "HEA (y, z)"

def is_random(ansatz: str) -> bool:
    return ansatz == "Random PQC"

def best_row(df: pd.DataFrame, mask_fn):
    sub = df[df["ansatz"].apply(mask_fn)].copy()
    if sub.empty:
        return None
    sub = sub.sort_values(
        ["f1_mean", "acc_mean", "loss_mean"],
        ascending=[False, False, True]
    )
    return sub.iloc[0]

def metric_or_dash(row, metric):
    if row is None:
        return "---"
    return f"{row[metric]:.3f}"

def latex_method_label(row, fallback):
    if row is None:
        return fallback
    name = row["ansatz"]
    name = name.replace("W1+W2", "W$_1$W$_2$")
    name = name.replace("_", r"\_")
    return name

def collect_dataset_block(df: pd.DataFrame, dataset_name: str):
    rows = []
    sub = df[df["dataset_name"] == dataset_name].copy()
    for q in sorted(sub["input_dim"].unique()):
        g = sub[sub["input_dim"] == q].copy()
        rows.append({
            "q": int(q),
            "hea": best_row(g, is_hea),
            "wi": best_row(g, is_wi),
            "mps": best_row(g, is_mps),
            "ttn": best_row(g, is_ttn),
            "random": best_row(g, is_random),
        })
    return rows

def build_dataset_table(dataset_name: str, label: str, caption: str) -> str:
    blocks = collect_dataset_block(summary5, dataset_name)

    lines = []
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{{label}}}")
    lines.append(r"\renewcommand{\arraystretch}{1.15}")
    lines.append(r"\setlength{\tabcolsep}{5pt}")
    lines.append(r"\footnotesize")
    lines.append(r"\begin{tabular}{lcccc}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Method} & \textbf{Acc.} & \textbf{Prec.} & \textbf{Rec.} & \textbf{F1} \\")
    lines.append(r"\midrule")

    first_block = True
    for block in blocks:
        if not first_block:
            lines.append(r"\midrule")
        first_block = False

        q = block["q"]
        lines.append(rf"\multicolumn{{5}}{{l}}{{\textbf{{{q} qubits}}}} \\")
        lines.append(r"\midrule")

        ordered = [
            ("HEA (y, z)", block["hea"]),
            (latex_method_label(block["wi"], "WI-PQC"), block["wi"]),
            (latex_method_label(block["mps"], "MPS"), block["mps"]),
            (latex_method_label(block["ttn"], "TTN"), block["ttn"]),
            ("Random PQC", block["random"]),
        ]

        for method_name, row in ordered:
            lines.append(
                rf"{method_name} & "
                rf"{metric_or_dash(row, 'acc_mean')} & "
                rf"{metric_or_dash(row, 'prec_mean')} & "
                rf"{metric_or_dash(row, 'rec_mean')} & "
                rf"{metric_or_dash(row, 'f1_mean')} \\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    return "\n".join(lines)

# ============================================================
# GENERATE TABLES
# ============================================================

iris_table = build_dataset_table(
    dataset_name="iris",
    label="tab:iris-summary",
    caption="Iris benchmark results. Entries are mean test accuracy, precision, recall, and F1 over 5 seeds."
)

wine_table = build_dataset_table(
    dataset_name="wine",
    label="tab:wine-summary",
    caption="Wine benchmark results. Entries are mean test accuracy, precision, recall, and F1 over 5 seeds."
)

diabetes_table = build_dataset_table(
    dataset_name="diabetes",
    label="tab:diabetes-summary",
    caption="Diabetes benchmark results. Entries are mean test accuracy, precision, recall, and F1 over 5 seeds."
)

print("===== IRIS TABLE =====")
print(iris_table)
print("\n")

print("===== WINE TABLE =====")
print(wine_table)
print("\n")

print("===== DIABETES TABLE =====")
print(diabetes_table)
print("\n")

# Save
out_dir = summary5_fp.parent
(out_dir / "latex_iris_summary_explicit.tex").write_text(iris_table)
(out_dir / "latex_wine_summary_explicit.tex").write_text(wine_table)
(out_dir / "latex_diabetes_summary_explicit.tex").write_text(diabetes_table)

print("Saved:")
print(out_dir / "latex_iris_summary_explicit.tex")
print(out_dir / "latex_wine_summary_explicit.tex")
print(out_dir / "latex_diabetes_summary_explicit.tex")

===== IRIS TABLE =====
\begin{table}[t]
\centering
\caption{Iris benchmark results. Entries are mean test accuracy, precision, recall, and F1 over 5 seeds.}
\label{tab:iris-summary}
\renewcommand{\arraystretch}{1.15}
\setlength{\tabcolsep}{5pt}
\footnotesize
\begin{tabular}{lcccc}
\toprule
\textbf{Method} & \textbf{Acc.} & \textbf{Prec.} & \textbf{Rec.} & \textbf{F1} \\
\midrule
\multicolumn{5}{l}{\textbf{4 qubits}} \\
\midrule
HEA & 0.607 & 0.644 & 0.607 & 0.599 \\
Best WI-PQC & 0.633 & 0.641 & 0.633 & 0.629 \\
Best TN baseline & 0.553 & 0.561 & 0.553 & 0.550 \\
Random PQC & 0.340 & 0.334 & 0.340 & 0.323 \\
\bottomrule
\end{tabular}
\end{table}


===== WINE TABLE =====
\begin{table}[t]
\centering
\caption{Wine benchmark results. Entries are mean test accuracy, precision, recall, and F1 over 5 seeds.}
\label{tab:wine-summary}
\renewcommand{\arraystretch}{1.15}
\setlength{\tabcolsep}{5pt}
\footnotesize
\begin{tabular}{lcccc}
\toprule
\textbf{Method} & \textbf{Acc.} & \textbf{Prec.} & \textbf{Rec.} & \textbf{F1} \\
\midrule
\multicolumn{5}{l}{\textbf{4 qubits}} \\
\midrule
HEA & 0.583 & 0.587 & 0.588 & 0.578 \\
Best WI-PQC & 0.650 & 0.664 & 0.647 & 0.649 \\
Best TN baseline & 0.567 & 0.577 & 0.569 & 0.559 \\
Random PQC & 0.422 & 0.471 & 0.437 & 0.396 \\
\midrule
\multicolumn{5}{l}{\textbf{6 qubits}} \\
\midrule
HEA & 0.417 & 0.440 & 0.429 & 0.396 \\
Best WI-PQC & 0.483 & 0.486 & 0.508 & 0.478 \\
Best TN baseline & 0.467 & 0.461 & 0.467 & 0.453 \\
Random PQC & 0.367 & 0.374 & 0.363 & 0.338 \\
\midrule
\multicolumn{5}{l}{\textbf{8 qubits}} \\
\midrule
HEA & 0.406 & 0.397 & 0.394 & 0.390 \\
Best WI-PQC & 0.444 & 0.427 & 0.436 & 0.424 \\
Best TN baseline & 0.428 & 0.419 & 0.422 & 0.416 \\
Random PQC & 0.322 & 0.327 & 0.324 & 0.315 \\
\bottomrule
\end{tabular}
\end{table}


===== DIABETES TABLE =====
\begin{table}[t]
\centering
\caption{Diabetes benchmark results. Entries are mean test accuracy, precision, recall, and F1 over 5 seeds.}
\label{tab:diabetes-summary}
\renewcommand{\arraystretch}{1.15}
\setlength{\tabcolsep}{5pt}
\footnotesize
\begin{tabular}{lcccc}
\toprule
\textbf{Method} & \textbf{Acc.} & \textbf{Prec.} & \textbf{Rec.} & \textbf{F1} \\
\midrule
\multicolumn{5}{l}{\textbf{4 qubits}} \\
\midrule
HEA & 0.648 & 0.489 & 0.350 & 0.407 \\
Best WI-PQC & 0.652 & 0.502 & 0.376 & 0.429 \\
Best TN baseline & 0.588 & 0.394 & 0.357 & 0.371 \\
Random PQC & 0.478 & 0.359 & 0.650 & 0.461 \\
\midrule
\multicolumn{5}{l}{\textbf{6 qubits}} \\
\midrule
HEA & 0.627 & 0.454 & 0.354 & 0.389 \\
Best WI-PQC & 0.658 & 0.509 & 0.342 & 0.408 \\
Best TN baseline & 0.599 & 0.410 & 0.372 & 0.386 \\
Random PQC & 0.503 & 0.364 & 0.582 & 0.447 \\
\midrule
\multicolumn{5}{l}{\textbf{8 qubits}} \\
\midrule
HEA & 0.622 & 0.432 & 0.293 & 0.349 \\
Best WI-PQC & 0.577 & 0.377 & 0.372 & 0.365 \\
Best TN baseline & 0.579 & 0.421 & 0.568 & 0.483 \\
Random PQC & 0.492 & 0.339 & 0.489 & 0.400 \\
\bottomrule
\end{tabular}
\end{table}


===== SELECTED METHODS =====
Iris 4q: Best WI-PQC = WI-PQC (W$\_1$W$\_2$+E, svd); Best TN = MPS (d=3)
Wine 4q: Best WI-PQC = WI-PQC (E) (greedy); Best TN = TTN (d=2)
Wine 6q: Best WI-PQC = WI-PQC (W$\_1$W$\_2$+E, chunking); Best TN = MPS (d=3)
Wine 8q: Best WI-PQC = WI-PQC (W$\_1$W$\_2$+E, chunking); Best TN = MPS (d=3)
Diabetes 4q: Best WI-PQC = WI-PQC (W+E, svd); Best TN = MPS (d=2)
Diabetes 6q: Best WI-PQC = WI-PQC (E) (greedy, cosine\_norm); Best TN = MPS (d=3)
Diabetes 8q: Best WI-PQC = WI-PQC (E) (greedy, top\_half); Best TN = MPS (d=2)

Saved:
/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/latex_iris_summary.tex
/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/latex_wine_summary.tex
/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/latex_diabetes_summary.tex

In [22]:
import pandas as pd
from pathlib import Path


merged_fp = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/wi_experiment_merged.csv")
df = pd.read_csv(merged_fp)

cdf = df[df["model_type"] == "classical"].copy()

classical_summary = (
    cdf.groupby(["dataset_name", "input_dim"])
       .agg(
           n_runs=("test_f1", "count"),
           acc_mean=("test_acc", "mean"),
           acc_std=("test_acc", "std"),
           prec_mean=("test_prec", "mean"),
           prec_std=("test_prec", "std"),
           rec_mean=("test_rec", "mean"),
           rec_std=("test_rec", "std"),
           f1_mean=("test_f1", "mean"),
           f1_std=("test_f1", "std"),
       )
       .reset_index()
       .sort_values(["dataset_name", "input_dim"])
)

print(classical_summary.to_string(index=False))

for _, r in classical_summary.iterrows():
    print(
        f'{r["dataset_name"].capitalize()} & {int(r["input_dim"])} & '
        f'{r["acc_mean"]:.3f} & {r["prec_mean"]:.3f} & {r["rec_mean"]:.3f} & {r["f1_mean"]:.3f} \\\\'
    )

dataset_name  input_dim  n_runs  acc_mean  acc_std  prec_mean  prec_std  rec_mean  rec_std  f1_mean   f1_std
    diabetes          4       5   0.68700 0.036597    0.44770  0.255556   0.48086 0.271018 0.461980 0.259492
    diabetes          6       5   0.73896 0.044608    0.63664  0.095277   0.62004 0.063203 0.622500 0.040202
    diabetes          8       5   0.71560 0.014092    0.59098  0.022703   0.58308 0.087989 0.583700 0.042232
        iris          4       4   0.94165 0.041948    0.94780  0.040038   0.94165 0.041948 0.941275 0.042127
        wine          4       5   0.92224 0.049691    0.93160  0.043134   0.92578 0.045130 0.924920 0.046843
        wine          6       5   0.95556 0.037245    0.95836  0.037216   0.95864 0.032429 0.957600 0.034812
        wine          8       5   0.96664 0.023259    0.96860  0.023988   0.96896 0.020484 0.967700 0.022234
Diabetes & 4 & 0.687 & 0.448 & 0.481 & 0.462 \\
Diabetes & 6 & 0.739 & 0.637 & 0.620 & 0.622 \\
Diabetes & 8 & 0.716 & 0.591 & 0.583 & 0.584 \\
Iris & 4 & 0.942 & 0.948 & 0.942 & 0.941 \\
Wine & 4 & 0.922 & 0.932 & 0.926 & 0.925 \\
Wine & 6 & 0.956 & 0.958 & 0.959 & 0.958 \\
Wine & 8 & 0.967 & 0.969 & 0.969 & 0.968 \\

In [26]:
# summary5 view for all anstaz with wi-pqc in it

summary5[summary5["ansatz"].str.contains("WI-PQC", na=False)].to_csv(Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/wi_pqc_only_summary5.csv"), index=False)

In [45]:
# summary5[summary5["ansatz"].str.contains("WI-PQC", na=False)]
_df = summary5[summary5["ansatz"].str.strip() == "WI-PQC (W1+W2+E, svd)"]
_df

,dataset_name,input_dim,ansatz,n_runs,acc_mean,acc_std,prec_mean,prec_std,rec_mean,rec_std,f1_mean,f1_std,loss_mean,loss_std,time_mean,time_std
9,diabetes,4,"WI-PQC (W1+W2+E, svd)",5,0.62600,0.066948,0.45642,0.125483,0.34586,0.064619,0.39218,0.085952,0.61400,0.042474,50.65168,0.659674
23,diabetes,6,"WI-PQC (W1+W2+E, svd)",5,0.65454,0.011577,0.49628,0.035066,0.25968,0.086581,0.33554,0.078929,0.64604,0.007813,221.59500,168.215397
43,diabetes,8,"WI-PQC (W1+W2+E, svd)",5,0.60782,0.041731,0.39714,0.074643,0.23300,0.065679,0.28798,0.058875,0.66812,0.009441,430.84154,6.912288
45,iris,4,"WI-PQC (W1+W2+E, svd)",5,0.63334,0.040825,0.64134,0.036594,0.63334,0.040825,0.62900,0.037750,0.93464,0.080559,9.75578,0.179841
62,wine,4,"WI-PQC (W1+W2+E, svd)",5,0.65554,0.050449,0.66226,0.062763,0.64858,0.059020,0.64108,0.057920,0.86808,0.030387,11.73034,0.158901
79,wine,6,"WI-PQC (W1+W2+E, svd)",5,0.46112,0.057609,0.46360,0.064718,0.48672,0.067311,0.45704,0.049714,1.05320,0.019946,51.56586,39.984464
95,wine,8,"WI-PQC (W1+W2+E, svd)",5,0.40556,0.063963,0.39700,0.070518,0.40112,0.052494,0.39228,0.064169,1.08620,0.007285,101.14654,1.637293

In [51]:
_df[_df["dataset_name"] == "diabetes"][['input_dim','acc_mean', 'prec_mean', 'rec_mean', 'f1_mean']]

    input_dim  acc_mean  prec_mean  rec_mean  f1_mean
9           4   0.62600    0.45642   0.34586  0.39218
23          6   0.65454    0.49628   0.25968  0.33554
43          8   0.60782    0.39714   0.23300  0.28798

In [44]:
# target_ansatz = "WI-PQC (W1+W2+E, svd)"
target_ansatz = "WI-PQC (W+E, svd)"

wipqc = summary5[summary5["ansatz"].str.contains("WI-PQC", na=False)].copy()
wipqc["ansatz"] = wipqc["ansatz"].str.strip()

group_cols = ["dataset_name", "input_dim"]

# ranks within each (dataset_name, input_dim) group
wipqc["acc_rank"] = (
    wipqc.groupby(group_cols)["acc_mean"]
    .rank(method="min", ascending=False)
)

wipqc["f1_rank"] = (
    wipqc.groupby(group_cols)["f1_mean"]
    .rank(method="min", ascending=False)
)

def summarize_group(g):
    target = g[g["ansatz"] == target_ansatz]
    best_acc = g.loc[[g["acc_mean"].idxmax()]].assign(selection="best_acc")
    worst_acc = g.loc[[g["acc_mean"].idxmin()]].assign(selection="worst_acc")
    best_f1 = g.loc[[g["f1_mean"].idxmax()]].assign(selection="best_f1")
    worst_f1 = g.loc[[g["f1_mean"].idxmin()]].assign(selection="worst_f1")

    parts = [
        target.assign(selection="target"),
        best_acc,
        worst_acc,
        best_f1,
        worst_f1,
    ]

    return pd.concat(parts)

result = (
    wipqc.groupby(group_cols, group_keys=False)
    .apply(summarize_group)
    .reset_index(drop=True)
)

result = result[
    [
        "selection",
        "dataset_name",
        "input_dim",
        "ansatz",
        "acc_mean",
        "acc_rank",
        "f1_mean",
        "f1_rank",
    ]
]

result

,selection,dataset_name,input_dim,ansatz,acc_mean,acc_rank,f1_mean,f1_rank
0,target,diabetes,4,"WI-PQC (W+E, svd)",0.65196,7.0,0.42858,1.0
1,best_acc,diabetes,4,"WI-PQC (E) (mwst, cosine_norm)",0.67404,1.0,0.42378,2.0
2,worst_acc,diabetes,4,"WI-PQC (W1+W2+E, svd)",0.62600,8.0,0.39218,8.0
3,best_f1,diabetes,4,"WI-PQC (W+E, svd)",0.65196,7.0,0.42858,1.0
4,worst_f1,diabetes,4,"WI-PQC (W1+W2+E, svd)",0.62600,8.0,0.39218,8.0
5,target,diabetes,6,"WI-PQC (W+E, svd)",0.64156,3.0,0.32074,5.0
6,best_acc,diabetes,6,"WI-PQC (E) (greedy, cosine_norm)",0.65842,1.0,0.40830,1.0
7,worst_acc,diabetes,6,"WI-PQC (E) (mwst, cosine_norm)",0.59610,8.0,0.32544,4.0
8,best_f1,diabetes,6,"WI-PQC (E) (greedy, cosine_norm)",0.65842,1.0,0.40830,1.0
9,worst_f1,diabetes,6,"WI-PQC (W1+W2+E, chunking)",0.60518,7.0,0.30344,8.0
10,target,diabetes,8,"WI-PQC (W+E, svd)",0.62726,2.0,0.29740,6.0
11,best_acc,diabetes,8,WI-PQC (E) (greedy),0.63118,1.0,0.30554,4.0
12,worst_acc,diabetes,8,"WI-PQC (E) (greedy, top_half)",0.57662,8.0,0.36464,1.0
13,best_f1,diabetes,8,"WI-PQC (E) (greedy, top_half)",0.57662,8.0,0.36464,1.0
14,worst_f1,diabetes,8,"WI-PQC (E) (mwst, cosine_norm)",0.61300,4.0,0.26012,8.0
15,target,iris,4,"WI-PQC (W+E, svd)",0.62668,2.0,0.61978,2.0
16,best_acc,iris,4,"WI-PQC (W1+W2+E, svd)",0.63334,1.0,0.62900,1.0
17,worst_acc,iris,4,WI-PQC (E) (greedy),0.57998,8.0,0.56152,8.0
18,best_f1,iris,4,"WI-PQC (W1+W2+E, svd)",0.63334,1.0,0.62900,1.0
19,worst_f1,iris,4,WI-PQC (E) (greedy),0.57998,8.0,0.56152,8.0
20,target,wine,4,"WI-PQC (W+E, svd)",0.62778,3.0,0.61922,3.0
21,best_acc,wine,4,"WI-PQC (W1+W2+E, svd)",0.65554,1.0,0.64108,2.0
22,worst_acc,wine,4,"WI-PQC (E) (greedy, top_half)",0.59442,8.0,0.57398,8.0
23,best_f1,wine,4,WI-PQC (E) (greedy),0.65000,2.0,0.64864,1.0
24,worst_f1,wine,4,"WI-PQC (E) (greedy, top_half)",0.59442,8.0,0.57398,8.0
25,target,wine,6,"WI-PQC (W+E, svd)",0.46666,3.0,0.45654,4.0
26,best_acc,wine,6,"WI-PQC (W1+W2+E, chunking)",0.48334,1.0,0.47838,1.0
27,worst_acc,wine,6,"WI-PQC (E) (greedy, top_half)",0.40002,8.0,0.39856,8.0
28,best_f1,wine,6,"WI-PQC (W1+W2+E, chunking)",0.48334,1.0,0.47838,1.0
29,worst_f1,wine,6,"WI-PQC (E) (greedy, top_half)",0.40002,8.0,0.39856,8.0
30,target,wine,8,"WI-PQC (W+E, svd)",0.36666,7.0,0.34358,7.0
31,best_acc,wine,8,"WI-PQC (W1+W2+E, chunking)",0.44444,1.0,0.42356,1.0
32,worst_acc,wine,8,"WI-PQC (E) (greedy, cosine_norm)",0.31112,8.0,0.29240,8.0
33,best_f1,wine,8,"WI-PQC (W1+W2+E, chunking)",0.44444,1.0,0.42356,1.0
34,worst_f1,wine,8,"WI-PQC (E) (greedy, cosine_norm)",0.31112,8.0,0.29240,8.0

In [40]:
wipqc.groupby("ansatz")[["acc_rank", "f1_rank"]].mean().sort_values("acc_rank")

                                  acc_rank   f1_rank
ansatz
WI-PQC (W1+W2+E, svd)             3.714286  4.000000
WI-PQC (W+E, svd)                 3.857143  4.000000
WI-PQC (E) (greedy)               4.142857  4.714286
WI-PQC (E) (greedy, cosine_norm)  4.285714  4.142857
WI-PQC (W1+W2+E, chunking)        4.285714  4.571429
WI-PQC (E) (mwst, cosine_norm)    4.428571  4.857143
WI-PQC (W+E, chunking)            4.714286  4.571429
WI-PQC (E) (greedy, top_half)     6.142857  5.142857

In [42]:
result.to_csv(Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/wipqc_ranking_analysis.csv"), index=False)

In [43]:
# Count how often each ansatz finishes in the top 3
top3_acc = (
    wipqc[wipqc["acc_rank"] <= 3]
    .groupby("ansatz")
    .size()
    .rename("top3_acc_count")
    .sort_values(ascending=False)
)

top3_f1 = (
    wipqc[wipqc["f1_rank"] <= 3]
    .groupby("ansatz")
    .size()
    .rename("top3_f1_count")
    .sort_values(ascending=False)
)

top3 = pd.concat([top3_acc, top3_f1], axis=1).fillna(0).astype(int)
top3["total_top3"] = top3["top3_acc_count"] + top3["top3_f1_count"]
top3.sort_values("total_top3", ascending=False)

                                  top3_acc_count  top3_f1_count  total_top3
ansatz
WI-PQC (W+E, svd)                              5              3           8
WI-PQC (W1+W2+E, svd)                          3              4           7
WI-PQC (E) (greedy)                            4              2           6
WI-PQC (E) (greedy, cosine_norm)               3              3           6
WI-PQC (E) (mwst, cosine_norm)                 3              2           5
WI-PQC (W1+W2+E, chunking)                     2              2           4
WI-PQC (W+E, chunking)                         1              3           4
WI-PQC (E) (greedy, top_half)                  1              2           3

In [57]:
import pandas as pd
from pathlib import Path

merged_fp = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/results/merged_analysis/wi_experiment_merged.csv")
df = pd.read_csv(merged_fp)

keep_dims = [4, 6, 8]

# --- Classical timings ---
cdf = df[(df["model_type"] == "classical") & (df["input_dim"].isin(keep_dims))].copy()
cdf["total_time"] = cdf["average_time_per_epoch"] * cdf["epochs"]

classical_timing = (
    cdf.groupby(["dataset_name", "input_dim"])
       .agg(
           n_runs=("total_time", "count"),
           time_per_epoch_mean=("average_time_per_epoch", "mean"),
           time_per_epoch_std=("average_time_per_epoch", "std"),
           total_time_mean=("total_time", "mean"),
           total_time_std=("total_time", "std"),
           epochs=("epochs", "first"),
       )
       .reset_index()
       .sort_values(["dataset_name", "input_dim"])
)

print("===== CLASSICAL TIMINGS =====")
print(classical_timing.to_string(index=False))
print()

# --- WI-PQC timings (averaged across all WI-PQC variants) ---
wdf = df[
    (df["model_type"] == "quantum") &
    (df["ansatz"].str.contains("WI-PQC", na=False)) &
    (df["input_dim"].isin(keep_dims))
].copy()
wdf["total_time"] = wdf["average_time_per_epoch"] * wdf["epochs"]

wdf["z"] = wdf.groupby(["dataset_name", "input_dim"])["total_time"].transform(
    lambda x: (x - x.mean()) / x.std()
)

outliers = wdf[wdf["z"].abs() > 2]
print(f"Removing {len(outliers)} outlier rows:")
print(outliers[["dataset_name", "input_dim", "ansatz", "seed", "total_time", "z"]].to_string(index=False))
print()

wdf_clean = wdf[wdf["z"].abs() <= 2].copy()


wipqc_timing = (
    wdf_clean.groupby(["dataset_name", "input_dim"])
       .agg(
           n_runs=("total_time", "count"),
           time_per_epoch_mean=("average_time_per_epoch", "mean"),
           time_per_epoch_std=("average_time_per_epoch", "std"),
           total_time_mean=("total_time", "mean"),
           total_time_std=("total_time", "std"),
           epochs=("epochs", "first"),
       )
       .reset_index()
       .sort_values(["dataset_name", "input_dim"])
)

print("===== WI-PQC TIMINGS (ALL VARIANTS AVERAGED) =====")
print(wipqc_timing.to_string(index=False))
print()

# --- Combined: total WI-PQC pipeline = classical pretrain + quantum train ---
combined = classical_timing[["dataset_name", "input_dim", "total_time_mean", "epochs"]].rename(
    columns={"total_time_mean": "classical_total", "epochs": "classical_epochs"}
).merge(
    wipqc_timing[["dataset_name", "input_dim", "total_time_mean", "epochs"]].rename(
        columns={"total_time_mean": "wipqc_total", "epochs": "quantum_epochs"}
    ),
    on=["dataset_name", "input_dim"],
    how="inner",
)
combined["pipeline_total"] = combined["classical_total"] + combined["wipqc_total"]

print("===== FULL WI-PQC PIPELINE TIME (classical + quantum) =====")
print(combined.to_string(index=False))

===== CLASSICAL TIMINGS =====
dataset_name  input_dim  n_runs  time_per_epoch_mean  time_per_epoch_std  total_time_mean  total_time_std  epochs
    diabetes          4       5              0.01316            0.001443            1.316        0.144326     100
    diabetes          6       5              0.01348            0.001938            1.348        0.193830     100
    diabetes          8       5              0.03950            0.002591            3.950        0.259133     100
        iris          4       4              0.00505            0.000768            0.505        0.076811     100
        wine          4       5              0.00538            0.000522            0.538        0.052154     100
        wine          6       5              0.00550            0.000866            0.550        0.086603     100
        wine          8       5              0.02036            0.000814            2.036        0.081425     100

Removing 8 outlier rows:
dataset_name  input_dim                         ansatz  seed  total_time        z
    diabetes          6          WI-PQC (W1+W2+E, svd)     2   15674.409 2.953394
    diabetes          4 WI-PQC (E) (mwst, cosine_norm)     3    8463.639 4.173120
    diabetes          4         WI-PQC (W+E, chunking)     3    6232.995 2.783962
    diabetes          4              WI-PQC (W+E, svd)     3    5882.568 2.565730
        wine          6              WI-PQC (W+E, svd)     3   13957.839 4.578184
        wine          6     WI-PQC (W1+W2+E, chunking)     4    7230.045 2.026606
    diabetes          6              WI-PQC (W+E, svd)     4   22810.470 4.829788
        wine          8     WI-PQC (W1+W2+E, chunking)     1    3191.163 2.033869

===== WI-PQC TIMINGS (ALL VARIANTS AVERAGED) =====
dataset_name  input_dim  n_runs  time_per_epoch_mean  time_per_epoch_std  total_time_mean  total_time_std  epochs
    diabetes          4      37            44.978708           19.546092      1349.361243      586.382752      30
    diabetes          6      38           122.116350           48.233766      3663.490500     1447.012988      30
    diabetes          8      40           334.153680           56.858255     10024.610400     1705.747664      30
        iris          4      40             7.500312            1.344893       225.009375       40.346777      30
        wine          4      40             9.050685            1.602630       271.520550       48.078896      30
        wine          6      38            47.605450           51.664730      1428.163500     1549.941909      30
        wine          8      39            78.000490           13.007589      2340.014692      390.227669      30

===== FULL WI-PQC PIPELINE TIME (classical + quantum) =====
dataset_name  input_dim  classical_total  classical_epochs  wipqc_total  quantum_epochs  pipeline_total
    diabetes          4            1.316               100  1349.361243              30     1350.677243
    diabetes          6            1.348               100  3663.490500              30     3664.838500
    diabetes          8            3.950               100 10024.610400              30    10028.560400
        iris          4            0.505               100   225.009375              30      225.514375
        wine          4            0.538               100   271.520550              30      272.058550
        wine          6            0.550               100  1428.163500              30     1428.713500
        wine          8            2.036               100  2340.014692              30     2342.050692

In [58]:
combined

,dataset_name,input_dim,classical_total,classical_epochs,wipqc_total,quantum_epochs,pipeline_total
0,diabetes,4,1.316,100,1349.361243,30,1350.677243
1,diabetes,6,1.348,100,3663.490500,30,3664.838500
2,diabetes,8,3.950,100,10024.610400,30,10028.560400
3,iris,4,0.505,100,225.009375,30,225.514375
4,wine,4,0.538,100,271.520550,30,272.058550
5,wine,6,0.550,100,1428.163500,30,1428.713500
6,wine,8,2.036,100,2340.014692,30,2342.050692

In [61]:
combined["classical_total_min"] = combined["classical_total"] / 60
combined["wipqc_total_min"] = combined["wipqc_total"] / 60
combined["pipeline_total_min"] = combined["pipeline_total"] / 60

combined[["dataset_name", "input_dim", "classical_total_min", "wipqc_total_min", "pipeline_total_min"]]

,dataset_name,input_dim,classical_total_min,wipqc_total_min,pipeline_total_min
0,diabetes,4,0.021933,22.489354,22.511287
1,diabetes,6,0.022467,61.058175,61.080642
2,diabetes,8,0.065833,167.076840,167.142673
3,iris,4,0.008417,3.750156,3.758573
4,wine,4,0.008967,4.525342,4.534309
5,wine,6,0.009167,23.802725,23.811892
6,wine,8,0.033933,39.000245,39.034178