In [10]:
# %% [markdown]
# # Shared Config

# %%
import os
import sys
import json
import time
import random
import importlib
from pathlib import Path
from argparse import Namespace

import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# ---------------------------------------------------------------------
# Shared project paths
# ---------------------------------------------------------------------
PROJECT_ROOT = Path("/Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design")
BENCHMARK_ROOT = PROJECT_ROOT / "utils" / "benchmarks"
TIMING_RESULTS_ROOT = BENCHMARK_ROOT / "timing_results"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------------------
# Shared experiment grid
# ---------------------------------------------------------------------
SEEDS = [0]
N_QUBITS = [4, 6, 8]

DATASETS = {
    "iris": (61, 4),
    "wine": (187, 13),
    "diabetes": (37, 8),
}

# ---------------------------------------------------------------------
# Shared runtime/training config
# ---------------------------------------------------------------------
BATCH_SIZE = 32
USE_GPU = False
VERBOSE_ON_FIT = False
DO_PCA = True

torch.set_num_threads(1)

# ---------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def iter_experiments():
    for seed in SEEDS:
        for n_qubits in N_QUBITS:
            for dataset_name, (dataset_id, n_features) in DATASETS.items():
                if n_qubits <= n_features:
                    yield {
                        "seed": seed,
                        "n_qubits": n_qubits,
                        "dataset_name": dataset_name,
                        "dataset_id": dataset_id,
                        "n_features": n_features,
                    }


def make_timings_dir(method_name: str, dataset_name: str, seed: int, n_qubits: int) -> Path:
    return TIMING_RESULTS_ROOT / method_name / dataset_name / f"seed_{seed}" / f"{n_qubits}qubits"

# QuantumDARTS

In [6]:
# %% [markdown]
# # QuantumDARTS

# %%
from QuantumDARTS.quantum_darts_model import QuantumDARTSModel
from QuantumDARTS.trainer import DARTSTrainer
from QuantumDARTS.utils import (
    GATE_POOL,
    load_mnist_data,
    load_openml_data,
    make_simple_multiclass_data,
)

QDARTS_CONFIG = {
    "learning_rate_arch": 0.01,
    "learning_rate_rot": 0.01,
    "perform_intermediate_eval": True,
    "eval_every": 2,
    "retraining_steps": 30,
    "retraining_lr": 0.01,
    "pilot_search_epochs": 5,
    "target_full_search_epochs": 10,
}


def quantumdarts_num_layers(n_qubits: int) -> int:
    return int(24 / n_qubits)


def build_darts_dataloaders(dataset_id, n_qubits, seed):
    if dataset_id == 0:
        n_classes = 3
        X_train, y_train, X_val, y_val, X_test, y_test = make_simple_multiclass_data(
            n_features=n_qubits,
            n_classes=n_classes,
            n_samples=500,
            cluster_std=0.01,
            random_state=42,
        )
    elif dataset_id == 1:
        X_train, y_train, X_val, y_val, X_test, y_test = load_mnist_data(
            n_features=n_qubits
        )
        n_classes = 2
    elif dataset_id in [61, 187, 37, 1510]:
        X_train, y_train, X_val, y_val, X_test, y_test = load_openml_data(
            dataset_id, n_features=n_qubits, seed=seed
        )
        n_classes = len(np.unique(y_train))
    else:
        raise ValueError(f"Unsupported dataset_id {dataset_id}")

    train_dataset = TensorDataset(
        torch.tensor(X_train, dtype=torch.float32),
        torch.tensor(y_train, dtype=torch.long),
    )
    val_dataset = TensorDataset(
        torch.tensor(X_val, dtype=torch.float32),
        torch.tensor(y_val, dtype=torch.long),
    )
    test_dataset = TensorDataset(
        torch.tensor(X_test, dtype=torch.float32),
        torch.tensor(y_test, dtype=torch.long),
    )

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    return train_dataset, val_dataset, test_dataset, train_loader, val_loader, test_loader, n_classes


def run_timed_quantumdarts(dataset_name, dataset_id, n_qubits, seed, timings_dir):
    n_layers = quantumdarts_num_layers(n_qubits)

    _, val_dataset, _, train_loader, val_loader, test_loader, n_classes = build_darts_dataloaders(
        dataset_id, n_qubits, seed
    )

    model = QuantumDARTSModel(
        n_qubits=n_qubits,
        n_layers=n_layers,
        gate_pool=GATE_POOL,
        n_classes=n_classes,
    )

    trainer = DARTSTrainer(
        model=model,
        train_loader=train_loader,
        validation_data=val_dataset,
        lr_arch=QDARTS_CONFIG["learning_rate_arch"],
        lr_rot=QDARTS_CONFIG["learning_rate_rot"],
    )

    search_t0 = time.perf_counter()
    trainer.search(
        num_epochs=QDARTS_CONFIG["pilot_search_epochs"],
        perform_eval=QDARTS_CONFIG["perform_intermediate_eval"],
        eval_every=QDARTS_CONFIG["eval_every"],
    )
    measured_pilot_search_time_sec = time.perf_counter() - search_t0

    estimated_full_search_time_sec = (
        measured_pilot_search_time_sec / QDARTS_CONFIG["pilot_search_epochs"]
    ) * QDARTS_CONFIG["target_full_search_epochs"]

    derive_t0 = time.perf_counter()
    _final_circuit = trainer.derive_best_circuit()
    derive_time_sec = time.perf_counter() - derive_t0

    reported_search_time_sec = estimated_full_search_time_sec + derive_time_sec

    train_t0 = time.perf_counter()
    _ = trainer.final_evaluation(
        train_loader,
        val_loader,
        test_loader,
        QDARTS_CONFIG["retraining_steps"],
        QDARTS_CONFIG["retraining_lr"],
    )
    measured_final_train_time_sec = time.perf_counter() - train_t0

    reported_train_time_sec = measured_final_train_time_sec
    reported_total_time_sec = reported_search_time_sec + reported_train_time_sec

    output = {
        "method": "QuantumDARTS",
        "dataset": dataset_name,
        "seed": int(seed),
        "qubits": int(n_qubits),
        "runtime_table_sec": {
            "search": float(reported_search_time_sec),
            "train": float(reported_train_time_sec),
            "total": float(reported_total_time_sec),
        },
        "timings_sec": {
            "measured_pilot_search_time_sec": float(measured_pilot_search_time_sec),
            "estimated_full_search_time_sec": float(estimated_full_search_time_sec),
            "derive_time_sec": float(derive_time_sec),
            "measured_final_train_time_sec": float(measured_final_train_time_sec),
        },
        "pilot_config": {
            "pilot_search_epochs": int(QDARTS_CONFIG["pilot_search_epochs"]),
        },
        "full_config": {
            "target_full_search_epochs": int(QDARTS_CONFIG["target_full_search_epochs"]),
            "retraining_steps": int(QDARTS_CONFIG["retraining_steps"]),
        },
    }

    os.makedirs(timings_dir, exist_ok=True)
    out_fp = os.path.join(timings_dir, "final_results.json")
    with open(out_fp, "w") as f:
        json.dump(output, f, indent=2)

    print(f"[INFO] Saved timing-only results to {out_fp}")


if __name__ == "__main__":
    for exp in iter_experiments():
        set_seed(exp["seed"])
        run_timed_quantumdarts(
            dataset_name=exp["dataset_name"],
            dataset_id=exp["dataset_id"],
            n_qubits=exp["n_qubits"],
            seed=exp["seed"],
            timings_dir=str(make_timings_dir("QuantumDARTS", exp["dataset_name"], exp["seed"], exp["n_qubits"])),
        )

[env] Loading OpenML data for dataset ID: 61
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:48<06:26, 128.90s/it, acc=0.3448, loss=1.4927]

epoch=2 pred_hist=[24, 5, 0] val_acc=0.2759

Searching:  80%|████████  | 4/5 [07:23<02:04, 124.05s/it, acc=0.3793, loss=1.7582]

epoch=4 pred_hist=[21, 7, 1] val_acc=0.2759

Searching: 100%|██████████| 5/5 [07:59<00:00, 95.83s/it, loss=1.4855]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/3 [00:00<?, ?it/s]

Test Results: Loss=1.0933, Acc=0.3333, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/iris/seed_0/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:36<06:06, 122.03s/it, acc=0.4167, loss=1.3009]

epoch=2 pred_hist=[30, 4, 2] val_acc=0.3333

Searching:  80%|████████  | 4/5 [06:59<01:57, 117.54s/it, acc=0.3056, loss=2.0146]

epoch=4 pred_hist=[27, 8, 1] val_acc=0.3611

Searching: 100%|██████████| 5/5 [07:33<00:00, 90.75s/it, loss=1.6014]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.1263, Acc=0.2222, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_0/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [04:11<07:04, 141.60s/it, acc=0.5974, loss=0.7247]

epoch=2 pred_hist=[69, 85] val_acc=0.3831

Searching:  80%|████████  | 4/5 [08:07<02:16, 136.34s/it, acc=0.5909, loss=0.8860]

epoch=4 pred_hist=[33, 121] val_acc=0.3571

Searching: 100%|██████████| 5/5 [08:47<00:00, 105.40s/it, loss=0.8502]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.7103, Acc=0.4610, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_0/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [06:06<10:20, 206.72s/it, acc=0.5000, loss=1.2739]

epoch=2 pred_hist=[36, 0, 0] val_acc=0.3333

Searching:  80%|████████  | 4/5 [11:52<03:19, 199.73s/it, acc=0.5000, loss=1.3583]

epoch=4 pred_hist=[30, 2, 4] val_acc=0.3889

Searching: 100%|██████████| 5/5 [12:50<00:00, 154.03s/it, loss=1.3128]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0676, Acc=0.4444, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_0/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [07:04<11:57, 239.03s/it, acc=0.4740, loss=0.7484]

epoch=2 pred_hist=[67, 87] val_acc=0.5390

Searching:  80%|████████  | 4/5 [13:46<03:51, 231.49s/it, acc=0.5325, loss=0.7536]

epoch=4 pred_hist=[80, 74] val_acc=0.5974

Searching: 100%|██████████| 5/5 [14:53<00:00, 178.64s/it, loss=0.7434]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.7017, Acc=0.4545, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_0/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [09:41<16:23, 327.84s/it, acc=0.4722, loss=1.4910]

epoch=2 pred_hist=[36, 0, 0] val_acc=0.3333

Searching:  80%|████████  | 4/5 [18:52<05:17, 317.28s/it, acc=0.4722, loss=1.2777]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [20:22<00:00, 244.60s/it, loss=1.3777]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.1060, Acc=0.3333, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_0/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [11:18<19:05, 381.91s/it, acc=0.4740, loss=0.7424]

epoch=2 pred_hist=[91, 63] val_acc=0.5390

Searching:  80%|████████  | 4/5 [21:56<06:08, 368.43s/it, acc=0.5195, loss=0.6834]

epoch=4 pred_hist=[94, 60] val_acc=0.5455

Searching: 100%|██████████| 5/5 [23:42<00:00, 284.43s/it, loss=0.7052]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6949, Acc=0.4740, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_0/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 61
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:21<05:38, 112.69s/it, acc=0.3103, loss=1.1402]

epoch=2 pred_hist=[14, 13, 2] val_acc=0.4138

Searching:  80%|████████  | 4/5 [06:46<01:53, 113.96s/it, acc=0.5172, loss=1.1893]

epoch=4 pred_hist=[23, 1, 5] val_acc=0.2414

Searching: 100%|██████████| 5/5 [07:18<00:00, 87.76s/it, loss=1.0965]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/3 [00:00<?, ?it/s]

Test Results: Loss=1.0751, Acc=0.4000, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/iris/seed_1/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:03<05:07, 102.49s/it, acc=0.4167, loss=1.3302]

epoch=2 pred_hist=[32, 4, 0] val_acc=0.2500

Searching:  80%|████████  | 4/5 [06:10<01:43, 103.93s/it, acc=0.5000, loss=1.4084]

epoch=4 pred_hist=[32, 3, 1] val_acc=0.3333

Searching: 100%|██████████| 5/5 [06:39<00:00, 79.92s/it, loss=1.7942]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0268, Acc=0.5278, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_1/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:33<05:57, 119.26s/it, acc=0.5390, loss=0.6927]

epoch=2 pred_hist=[53, 101] val_acc=0.4935

Searching:  80%|████████  | 4/5 [07:11<02:00, 120.92s/it, acc=0.5390, loss=0.7503]

epoch=4 pred_hist=[57, 97] val_acc=0.5455

Searching: 100%|██████████| 5/5 [07:45<00:00, 93.08s/it, loss=0.6964]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.7030, Acc=0.4481, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_1/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [05:10<08:41, 173.70s/it, acc=0.4167, loss=1.2828]

epoch=2 pred_hist=[35, 0, 1] val_acc=0.3333

Searching:  80%|████████  | 4/5 [10:30<02:56, 176.91s/it, acc=0.4167, loss=1.4795]

epoch=4 pred_hist=[32, 4, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [11:19<00:00, 135.95s/it, loss=1.4139]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0951, Acc=0.4167, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_1/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [06:02<10:07, 202.46s/it, acc=0.5974, loss=0.6722]

epoch=2 pred_hist=[54, 100] val_acc=0.4870

Searching:  80%|████████  | 4/5 [12:08<03:23, 203.60s/it, acc=0.5974, loss=0.6858]

epoch=4 pred_hist=[87, 67] val_acc=0.5195

Searching: 100%|██████████| 5/5 [13:05<00:00, 157.07s/it, loss=0.6855]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6896, Acc=0.5130, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_1/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [08:17<13:54, 278.31s/it, acc=0.4167, loss=1.2510]

epoch=2 pred_hist=[36, 0, 0] val_acc=0.3333

Searching:  80%|████████  | 4/5 [16:43<04:41, 281.16s/it, acc=0.3889, loss=1.4544]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [18:02<00:00, 216.43s/it, loss=1.2251]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.1078, Acc=0.3333, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_1/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [09:34<16:02, 320.83s/it, acc=0.6169, loss=0.7749]

epoch=2 pred_hist=[20, 134] val_acc=0.4221

Searching:  80%|████████  | 4/5 [19:13<05:22, 322.68s/it, acc=0.3831, loss=0.7168]

epoch=4 pred_hist=[77, 77] val_acc=0.4935

Searching: 100%|██████████| 5/5 [20:45<00:00, 249.06s/it, loss=0.7234]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6913, Acc=0.5260, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_1/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 61
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:27<05:46, 115.59s/it, acc=0.4138, loss=1.1759]

epoch=2 pred_hist=[19, 1, 9] val_acc=0.1379

Searching:  80%|████████  | 4/5 [06:55<01:55, 115.92s/it, acc=0.4483, loss=1.4749]

epoch=4 pred_hist=[19, 7, 3] val_acc=0.3793

Searching: 100%|██████████| 5/5 [07:29<00:00, 89.85s/it, loss=1.1988]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/3 [00:00<?, ?it/s]

Test Results: Loss=1.0270, Acc=0.4000, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/iris/seed_2/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:05<05:11, 103.77s/it, acc=0.5000, loss=0.7890]

epoch=2 pred_hist=[28, 0, 8] val_acc=0.4722

Searching:  80%|████████  | 4/5 [06:13<01:44, 104.36s/it, acc=0.5000, loss=1.2337]

epoch=4 pred_hist=[20, 9, 7] val_acc=0.3889

Searching: 100%|██████████| 5/5 [06:43<00:00, 80.69s/it, loss=1.1814]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0966, Acc=0.3611, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_2/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:38<06:05, 121.92s/it, acc=0.5714, loss=0.7178]

epoch=2 pred_hist=[114, 40] val_acc=0.5714

Searching:  80%|████████  | 4/5 [07:18<02:02, 122.19s/it, acc=0.4221, loss=0.7574]

epoch=4 pred_hist=[58, 96] val_acc=0.3896

Searching: 100%|██████████| 5/5 [07:53<00:00, 94.71s/it, loss=0.6383]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6950, Acc=0.5065, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_2/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [05:14<08:47, 175.77s/it, acc=0.5000, loss=1.0381]

epoch=2 pred_hist=[30, 6, 0] val_acc=0.3056

Searching:  80%|████████  | 4/5 [10:33<02:56, 176.97s/it, acc=0.3889, loss=1.0994]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [11:24<00:00, 136.89s/it, loss=1.0872]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0799, Acc=0.3889, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_2/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [06:09<10:17, 205.79s/it, acc=0.4870, loss=0.6722]

epoch=2 pred_hist=[69, 85] val_acc=0.5130

Searching:  80%|████████  | 4/5 [12:16<03:25, 205.09s/it, acc=0.4870, loss=0.7354]

epoch=4 pred_hist=[69, 85] val_acc=0.5130

Searching: 100%|██████████| 5/5 [13:15<00:00, 159.16s/it, loss=0.7298]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6958, Acc=0.4870, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_2/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [08:17<13:54, 278.30s/it, acc=0.3889, loss=1.0498]

epoch=2 pred_hist=[35, 1, 0] val_acc=0.3333

Searching:  80%|████████  | 4/5 [16:42<04:40, 280.39s/it, acc=0.3889, loss=0.9862]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [18:03<00:00, 216.65s/it, loss=1.0482]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0962, Acc=0.3056, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_2/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [09:42<16:13, 324.60s/it, acc=0.5195, loss=0.7632]

epoch=2 pred_hist=[78, 76] val_acc=0.5065

Searching:  80%|████████  | 4/5 [19:26<05:25, 325.01s/it, acc=0.5130, loss=0.7044]

epoch=4 pred_hist=[138, 16] val_acc=0.6234

Searching: 100%|██████████| 5/5 [21:00<00:00, 252.01s/it, loss=0.6915]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6914, Acc=0.5260, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_2/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 61
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:58<06:40, 133.56s/it, acc=0.6897, loss=0.9620]

epoch=2 pred_hist=[23, 3, 3] val_acc=0.2759

Searching:  80%|████████  | 4/5 [08:07<02:18, 138.07s/it, acc=0.6207, loss=1.2420]

epoch=4 pred_hist=[25, 3, 1] val_acc=0.2759

Searching: 100%|██████████| 5/5 [08:47<00:00, 105.43s/it, loss=1.1864]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/3 [00:00<?, ?it/s]

Test Results: Loss=1.0928, Acc=0.4667, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/iris/seed_3/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:35<06:02, 120.81s/it, acc=0.5000, loss=1.2948]

epoch=2 pred_hist=[29, 4, 3] val_acc=0.3333

Searching:  80%|████████  | 4/5 [07:11<02:01, 121.40s/it, acc=0.4722, loss=1.3653]

epoch=4 pred_hist=[29, 6, 1] val_acc=0.3889

Searching: 100%|██████████| 5/5 [07:45<00:00, 93.02s/it, loss=1.1360]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=0.9826, Acc=0.5556, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_3/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [04:11<07:02, 140.68s/it, acc=0.5844, loss=0.6791]

epoch=2 pred_hist=[87, 67] val_acc=0.5260

Searching:  80%|████████  | 4/5 [08:32<02:24, 144.82s/it, acc=0.6104, loss=0.6569]

epoch=4 pred_hist=[111, 43] val_acc=0.5260

Searching: 100%|██████████| 5/5 [09:13<00:00, 110.69s/it, loss=0.6811]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6976, Acc=0.4740, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_3/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [06:00<10:06, 202.18s/it, acc=0.3889, loss=1.3329]

epoch=2 pred_hist=[35, 1, 0] val_acc=0.3056

Searching:  80%|████████  | 4/5 [12:18<03:29, 209.29s/it, acc=0.3889, loss=1.4415]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [13:17<00:00, 159.47s/it, loss=1.4126]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0870, Acc=0.3611, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_3/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [07:02<11:48, 236.08s/it, acc=0.5390, loss=0.7600]

epoch=2 pred_hist=[86, 68] val_acc=0.5455

Searching:  80%|████████  | 4/5 [14:18<04:02, 242.55s/it, acc=0.5390, loss=0.6328]

epoch=4 pred_hist=[121, 33] val_acc=0.6169

Searching: 100%|██████████| 5/5 [15:27<00:00, 185.47s/it, loss=0.7058]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6943, Acc=0.4805, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_3/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [09:28<15:54, 318.05s/it, acc=0.3889, loss=1.1901]

epoch=2 pred_hist=[36, 0, 0] val_acc=0.3333

Searching:  80%|████████  | 4/5 [19:25<05:30, 330.67s/it, acc=0.3889, loss=1.1286]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [20:59<00:00, 251.92s/it, loss=1.2832]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0882, Acc=0.2500, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_3/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [11:04<18:32, 370.86s/it, acc=0.6364, loss=0.6909]

epoch=2 pred_hist=[85, 69] val_acc=0.5649

Searching:  80%|████████  | 4/5 [22:32<06:22, 382.40s/it, acc=0.6364, loss=0.7112]

epoch=4 pred_hist=[113, 41] val_acc=0.5779

Searching: 100%|██████████| 5/5 [24:21<00:00, 292.34s/it, loss=0.7101]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6958, Acc=0.4545, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_3/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 61
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:48<06:21, 127.15s/it, acc=0.4138, loss=1.1903]

epoch=2 pred_hist=[18, 6, 5] val_acc=0.3793

Searching:  80%|████████  | 4/5 [07:28<02:05, 125.14s/it, acc=0.4138, loss=1.3008]

epoch=4 pred_hist=[18, 6, 5] val_acc=0.4483

Searching: 100%|██████████| 5/5 [07:59<00:00, 95.98s/it, loss=1.3446]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/3 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/3 [00:00<?, ?it/s]

Test Results: Loss=0.9917, Acc=0.4667, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/iris/seed_4/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [03:26<05:45, 115.08s/it, acc=0.3611, loss=1.1358]

epoch=2 pred_hist=[18, 10, 8] val_acc=0.5000

Searching:  80%|████████  | 4/5 [06:46<01:53, 113.57s/it, acc=0.3889, loss=1.3311]

epoch=4 pred_hist=[30, 3, 3] val_acc=0.3056

Searching: 100%|██████████| 5/5 [07:14<00:00, 86.87s/it, loss=1.2273]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0418, Acc=0.4444, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_4/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [04:01<06:42, 134.15s/it, acc=0.5195, loss=0.7662]

epoch=2 pred_hist=[91, 63] val_acc=0.4481

Searching:  80%|████████  | 4/5 [07:51<02:11, 131.31s/it, acc=0.5519, loss=0.7054]

epoch=4 pred_hist=[110, 44] val_acc=0.5844

Searching: 100%|██████████| 5/5 [08:23<00:00, 100.78s/it, loss=0.6759]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6881, Acc=0.5519, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_4/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [05:48<09:42, 194.27s/it, acc=0.3611, loss=1.1282]

epoch=2 pred_hist=[34, 0, 2] val_acc=0.3333

Searching:  80%|████████  | 4/5 [11:24<03:11, 191.40s/it, acc=0.3611, loss=1.2438]

epoch=4 pred_hist=[35, 1, 0] val_acc=0.3611

Searching: 100%|██████████| 5/5 [12:11<00:00, 146.39s/it, loss=1.2594]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.0898, Acc=0.4167, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_4/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [06:45<11:15, 225.05s/it, acc=0.5584, loss=0.7010]

epoch=2 pred_hist=[86, 68] val_acc=0.5065

Searching:  80%|████████  | 4/5 [13:11<03:40, 220.59s/it, acc=0.5974, loss=0.7071]

epoch=4 pred_hist=[65, 89] val_acc=0.4610

Searching: 100%|██████████| 5/5 [14:05<00:00, 169.20s/it, loss=0.7072]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6947, Acc=0.4805, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_4/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [09:08<15:16, 305.34s/it, acc=0.3889, loss=1.1627]

epoch=2 pred_hist=[36, 0, 0] val_acc=0.3333

Searching:  80%|████████  | 4/5 [17:59<05:02, 302.08s/it, acc=0.3889, loss=1.0154]

epoch=4 pred_hist=[36, 0, 0] val_acc=0.3333

Searching: 100%|██████████| 5/5 [19:14<00:00, 230.82s/it, loss=1.4582]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

Test Results: Loss=1.1126, Acc=0.1944, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/wine/seed_4/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.

Searching:  40%|████      | 2/5 [10:40<17:47, 355.87s/it, acc=0.4545, loss=0.6841]

epoch=2 pred_hist=[84, 70] val_acc=0.5195

Searching:  80%|████████  | 4/5 [20:57<05:50, 350.82s/it, acc=0.5584, loss=0.6685]

epoch=4 pred_hist=[83, 71] val_acc=0.5130

Searching: 100%|██████████| 5/5 [22:23<00:00, 268.69s/it, loss=0.6897]

--- Starting Final Evaluation ---
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Epoch 1/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/15 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/15 [00:00<?, ?it/s]

Test Results: Loss=0.6756, Acc=0.5519, F1=0.0000
[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/QuantumDARTS/diabetes/seed_4/8qubits/final_results.json

# TF-QAS

In [9]:
# %% [markdown]
# # TF-QAS

# %%
from utils.data.preprocessing import data_pipeline
from utils.nn.QuantumNN import QuantumNN
from utils.ansatze.HierarchicalGatewise import HierarchicalGatewiseAnsatz
from utils.ansatze.HierarchicalLayerwise import HierarchicalLayerwiseAnsatz

exp_module = importlib.import_module("TF-QAS.expressibility_proxy")
path_module = importlib.import_module("TF-QAS.path_proxy")

calculate_expressibility_proxy = exp_module.calculate_expressibility_proxy
calculate_path_proxy = path_module.calculate_path_proxy

TFQAS_CONFIG = {
    "quantum_lr": 0.05,
    "pilot_s": 200,
    "pilot_r": 20,
    "pilot_k": 5,
    "pilot_epochs_quantum": 5,
    "full_s": 50000,
    "full_r": 5000,
    "full_k": 50,
    "full_epochs_quantum": 30,
    "mode": "gate",  # or "layer"
}


def run_tf_qas_timed(ansatze_class, ansatz_args, S, R, K):
    qas_t0 = time.perf_counter()

    initial_circuits = []
    for i in range(S):
        ansatz = ansatze_class(**ansatz_args, seed=i)
        initial_circuits.append({"seed": i, "ansatz": ansatz})

    for circuit_data in initial_circuits:
        path_count = calculate_path_proxy(circuit_data["ansatz"].get_ansatz())
        circuit_data["path_count"] = path_count

    sorted_by_path = sorted(initial_circuits, key=lambda x: x["path_count"], reverse=True)
    top_R_circuits = sorted_by_path[:R]

    for circuit_data in top_R_circuits:
        expressibility = calculate_expressibility_proxy(
            circuit_data["ansatz"].get_ansatz(),
            n_samples=200,
        )
        circuit_data["expressibility"] = expressibility

    sorted_by_expressibility = sorted(
        top_R_circuits,
        key=lambda x: x["expressibility"],
        reverse=True,
    )
    top_K_circuits = sorted_by_expressibility[:K]

    qas_time_sec = time.perf_counter() - qas_t0
    return top_K_circuits, qas_time_sec


def train_candidate_once(
    circuit,
    input_dim,
    output_dim,
    train_loader_q,
    val_loader_q,
    test_loader_q,
    epochs,
    seed,
):
    set_seed(seed)

    model_q = QuantumNN(
        ansatz=circuit.get_ansatz(),
        n_qubits=input_dim,
        num_classes=output_dim,
        use_gpu=USE_GPU,
        gradient_method="guided_spsa",
    )

    optimizer_q = optim.Adam(model_q.parameters(), lr=TFQAS_CONFIG["quantum_lr"])
    scheduler_q = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer_q,
        mode="min",
        factor=0.3,
        patience=max(1, epochs // 5),
        min_lr=1e-4,
        verbose=False,
    )

    t0 = time.perf_counter()
    model_q.fit(
        train_loader_q,
        val_loader_q,
        epochs=epochs,
        optimizer=optimizer_q,
        scheduler=scheduler_q,
        verbose=VERBOSE_ON_FIT,
        eval_every=2,
    )
    train_time_sec = time.perf_counter() - t0

    eval_output_q = model_q.evaluate(test_loader_q, verbose=False)
    metrics = {
        "test_loss": eval_output_q[0],
        "test_acc": eval_output_q[1],
        "test_prec": eval_output_q[2],
        "test_rec": eval_output_q[3],
        "test_f1": eval_output_q[4],
    }
    return metrics, train_time_sec


def run_timed_tf_qas(dataset_name, openml_dataset_id, n_qubits, seed, timings_dir):
    _, quantum_data, input_dim, output_dim, _ = data_pipeline(
        openml_dataset_id,
        batch_size=BATCH_SIZE,
        do_pca=DO_PCA,
        use_gpu=USE_GPU,
        n_components=n_qubits,
        seed=seed,
    )

    (
        x_train_q,
        x_val_q,
        x_test_q,
        y_train_q,
        y_val_q,
        y_test_q,
        train_loader_q,
        val_loader_q,
        test_loader_q,
    ) = quantum_data

    ansatz_args = {"n_qubits": n_qubits}
    if TFQAS_CONFIG["mode"] == "gate":
        ansatze_class = HierarchicalGatewiseAnsatz
        ansatz_args["n_gates"] = 24
        ansatz_args["temporal_bias"] = 0.75
        ansatz_args["spatial_bias"] = 1.0
    elif TFQAS_CONFIG["mode"] == "layer":
        ansatze_class = HierarchicalLayerwiseAnsatz
        ansatz_args["depth"] = 4
    else:
        raise ValueError("mode must be 'gate' or 'layer'")

    candidate_circuits, measured_qas_stage_time_sec = run_tf_qas_timed(
        ansatze_class,
        ansatz_args,
        TFQAS_CONFIG["pilot_s"],
        TFQAS_CONFIG["pilot_r"],
        TFQAS_CONFIG["pilot_k"],
    )

    candidate_training_time_sec = 0.0
    best_test_f1 = -1.0
    best_circuit = None

    for ansatz_data in candidate_circuits:
        circuit = ansatz_data["ansatz"]
        metrics, this_train_time_sec = train_candidate_once(
            circuit=circuit,
            input_dim=input_dim,
            output_dim=output_dim,
            train_loader_q=train_loader_q,
            val_loader_q=val_loader_q,
            test_loader_q=test_loader_q,
            epochs=TFQAS_CONFIG["pilot_epochs_quantum"],
            seed=seed,
        )
        candidate_training_time_sec += this_train_time_sec

        if metrics["test_f1"] > best_test_f1:
            best_test_f1 = metrics["test_f1"]
            best_circuit = circuit

    estimated_qas_stage_time_sec = (
        measured_qas_stage_time_sec * (TFQAS_CONFIG["full_s"] / TFQAS_CONFIG["pilot_s"])
    )
    estimated_candidate_training_time_sec = (
        candidate_training_time_sec
        * (TFQAS_CONFIG["full_k"] / TFQAS_CONFIG["pilot_k"])
        * (TFQAS_CONFIG["full_epochs_quantum"] / TFQAS_CONFIG["pilot_epochs_quantum"])
    )

    reported_search_time_sec = (
        estimated_qas_stage_time_sec + estimated_candidate_training_time_sec
    )

    _, measured_final_retrain_time_sec = train_candidate_once(
        circuit=best_circuit,
        input_dim=input_dim,
        output_dim=output_dim,
        train_loader_q=train_loader_q,
        val_loader_q=val_loader_q,
        test_loader_q=test_loader_q,
        epochs=TFQAS_CONFIG["full_epochs_quantum"],
        seed=seed,
    )

    reported_train_time_sec = measured_final_retrain_time_sec
    reported_total_time_sec = reported_search_time_sec + reported_train_time_sec

    output_data = {
        "method": "TF-QAS",
        "dataset": dataset_name,
        "seed": int(seed),
        "qubits": int(n_qubits),
        "runtime_table_sec": {
            "search": float(reported_search_time_sec),
            "train": float(reported_train_time_sec),
            "total": float(reported_total_time_sec),
        },
        "timings_sec": {
            "measured_qas_stage_time_sec": float(measured_qas_stage_time_sec),
            "candidate_training_time_sec_pilot": float(candidate_training_time_sec),
            "estimated_qas_stage_time_sec": float(estimated_qas_stage_time_sec),
            "estimated_candidate_training_time_sec": float(estimated_candidate_training_time_sec),
            "measured_final_retrain_time_sec": float(measured_final_retrain_time_sec),
        },
        "pilot_config": {
            "S": int(TFQAS_CONFIG["pilot_s"]),
            "R": int(TFQAS_CONFIG["pilot_r"]),
            "K": int(TFQAS_CONFIG["pilot_k"]),
            "epochs_quantum": int(TFQAS_CONFIG["pilot_epochs_quantum"]),
        },
        "full_config": {
            "S": int(TFQAS_CONFIG["full_s"]),
            "R": int(TFQAS_CONFIG["full_r"]),
            "K": int(TFQAS_CONFIG["full_k"]),
            "epochs_quantum": int(TFQAS_CONFIG["full_epochs_quantum"]),
        },
    }

    os.makedirs(timings_dir, exist_ok=True)
    out_fp = os.path.join(timings_dir, "final_results.json")
    with open(out_fp, "w") as f:
        json.dump(output_data, f, indent=2)

    print(f"[INFO] Saved timing-only results to {out_fp}")


if __name__ == "__main__":
    for exp in iter_experiments():
        set_seed(exp["seed"])
        run_timed_tf_qas(
            dataset_name=exp["dataset_name"],
            openml_dataset_id=exp["dataset_id"],
            n_qubits=exp["n_qubits"],
            seed=exp["seed"],
            timings_dir=str(make_timings_dir("TF-QAS", exp["dataset_name"], exp["seed"], exp["n_qubits"])),
        )

Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/iris/seed_0/4qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_0/4qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_0/4qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_0/6qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_0/6qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_0/8qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_0/8qubits/final_results.json
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/iris/seed_1/4qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_1/4qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_1/4qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_1/6qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_1/6qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_1/8qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_1/8qubits/final_results.json
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/iris/seed_2/4qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_2/4qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_2/4qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_2/6qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_2/6qubits/final_results.json
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/wine/seed_2/8qubits/final_results.json
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/TF-QAS/diabetes/seed_2/8qubits/final_results.json

# BenchRL-QAS

In [11]:
# %% [markdown]
# # BenchRL-QAS

# %%
NOTEBOOK_DIR = Path.cwd()
BENCHMARKS_DIR = NOTEBOOK_DIR
RL_VQC_DIR = BENCHMARKS_DIR / "RL-QAS-TPPO" / "VQC"
RL_CONFIG_DIR = RL_VQC_DIR / "configuration_files" / "TPPO"
BENCHRL_TIMING_ROOT = TIMING_RESULTS_ROOT / "BenchRL-QAS-TPPO"

for p in [PROJECT_ROOT, RL_VQC_DIR]:
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from vqc_helpers import get_config
from environment_VQC import CircuitEnv
import agents

from qiskit.circuit import QuantumCircuit as QkCircuit, Parameter

BENCHRL_CONFIG = {
    "pilot_episodes": 10,
    "full_episodes": 200,
    "final_train_epochs": 10,
    "final_train_lr": 0.05,
}


def modify_state(state, env, conf, device):
    if not torch.is_tensor(state):
        state = torch.tensor(state, dtype=torch.double, device=device)
    if conf["agent"]["en_state"]:
        if env.prev_energy is None:
            raise ValueError("env.prev_energy is None; ensure CircuitEnv.step() sets it correctly")
        prev_energy = torch.tensor(float(env.prev_energy), dtype=torch.double, device=device).unsqueeze(0)
        state = torch.cat((state, prev_energy))
    if "threshold_in_state" in conf["agent"].keys() and conf["agent"]["threshold_in_state"]:
        done_threshold = torch.tensor([env.done_threshold], dtype=torch.double, device=device)
        state = torch.cat((state, done_threshold))
    return state


def modify_state_like_training(state, env, conf, device):
    if conf["agent"].get("en_state", 0):
        state = torch.cat((state, torch.tensor(env.prev_energy, dtype=torch.float, device=device).view(1)))
    if conf["agent"].get("threshold_in_state", 0):
        state = torch.cat((state, torch.tensor(env.done_threshold, dtype=torch.float, device=device).view(1)))
    return state


def greedy_eval_episode(env, agent, device, conf):
    state = env.reset().clone().detach().to(dtype=torch.double, device=device)
    state = modify_state_like_training(state, env, conf, device)

    for _ in range(env.num_layers + 1):
        illegal = env.illegal_action_new()
        with torch.no_grad():
            logits = agent.policy(state)
            probs = torch.softmax(logits, dim=-1)
            if illegal is not None:
                probs[illegal] = 0
                probs = probs / probs.sum()
            action = torch.argmax(probs).item()

        next_state, reward, done = env.step(agent.translate[action])
        next_state = next_state.clone().detach().to(dtype=torch.double, device=device)
        next_state = modify_state_like_training(next_state, env, conf, device)
        state = next_state

        if done:
            break

    from qulacs import ParametricQuantumCircuit as PQC

    if hasattr(env, "get_parametric_circuit"):
        try:
            circ = env.get_parametric_circuit()
            if circ is not None:
                return circ
        except Exception:
            pass

    for name in ("ansatz", "circuit", "parametric_circuit", "pq_circuit"):
        if hasattr(env, name):
            circ = getattr(env, name)
            try:
                if isinstance(circ, PQC):
                    return circ
            except Exception:
                return circ

    if hasattr(env, "make_circuit"):
        try:
            circ = env.make_circuit()
            if circ is not None:
                setattr(env, "ansatz", circ)
                return circ
        except Exception:
            pass

    try:
        for _, v in env.__dict__.items():
            if isinstance(v, PQC):
                return v
    except Exception:
        pass

    return None


def one_episode(episode_no, env, agent, episodes, conf):
    t0 = time.time()
    agent.saver.get_new_episode("train", episode_no)
    state = env.reset()
    agent.saver.stats_file["train"][episode_no]["done_threshold"] = env.done_threshold

    state = modify_state(state, env, conf, agent.device)

    done = False
    for _ in range(env.num_layers + 1):
        action, log_prob = agent.act(state)
        next_state, reward, done = env.step(agent.translate[action])
        agent.rewards.append(reward.item() if torch.is_tensor(reward) else reward)

        agent.saver.stats_file["train"][episode_no]["actions"].append(action)
        agent.saver.stats_file["train"][episode_no]["errors"].append(env.error)
        agent.saver.stats_file["train"][episode_no]["errors_test"].append(env.error_test)
        agent.saver.stats_file["train"][episode_no]["rewards"].append(env.current_reward)
        agent.saver.stats_file["train"][episode_no]["time"].append(time.time() - t0)

        next_state = modify_state(next_state, env, conf, agent.device)
        state = next_state

        if done:
            break

    agent.update()
    agent.saver.validate_stats(episode_no, "train")


def train(agent, env, episodes, seed, output_path, threshold, conf):
    for e in range(episodes):
        one_episode(e, env, agent, episodes, conf)


class Saver:
    def __init__(self, results_path, experiment_seed):
        self.stats_file = {"train": {}, "test": {}}
        self.exp_seed = experiment_seed
        self.rpath = results_path

    def get_new_episode(self, mode, episode_no):
        if mode == "train":
            self.stats_file[mode][episode_no] = {
                "loss_policy": [],
                "loss_value": [],
                "actions": [],
                "errors": [],
                "errors_test": [],
                "done_threshold": 0,
                "bond_distance": 0,
                "nfev": [],
                "opt_ang": [],
                "time": [],
                "rewards": [],
            }

    def validate_stats(self, episode, mode):
        assert len(self.stats_file[mode][episode]["actions"]) == len(self.stats_file[mode][episode]["errors"])


def convert_qulacs_to_qiskit(qulacs_circuit):
    num_qubits = qulacs_circuit.get_qubit_count()
    qiskit_qc = QkCircuit(num_qubits)
    param_index = 0

    gate_count = qulacs_circuit.get_gate_count()
    for i in range(gate_count):
        gate = qulacs_circuit.get_gate(i)
        name = gate.get_name()
        targets = gate.get_target_index_list()
        controls = gate.get_control_index_list()

        if name == "CNOT":
            qiskit_qc.cx(controls[0], targets[0])
        elif name == "ParametricRY":
            theta = Parameter(f"θ{param_index}")
            qiskit_qc.ry(theta, targets[0])
            param_index += 1
        elif name == "ParametricRX":
            theta = Parameter(f"θ{param_index}")
            qiskit_qc.rx(theta, targets[0])
            param_index += 1
        elif name == "ParametricRZ":
            theta = Parameter(f"θ{param_index}")
            qiskit_qc.rz(theta, targets[0])
            param_index += 1
        elif name == "X":
            qiskit_qc.x(targets[0])
        elif name == "H":
            qiskit_qc.h(targets[0])
        else:
            print(f"Warning: Skipping unsupported gate for conversion: {name}")

    return qiskit_qc


def build_quantum_dataloaders(openml_dataset_id: int, n_qubits: int, seed: int):
    _, quantum_data, input_dim, output_dim, _ = data_pipeline(
        openml_dataset_id=openml_dataset_id,
        n_components=n_qubits,
        do_pca=DO_PCA,
        batch_size=BATCH_SIZE,
        seed=seed,
    )

    (
        x_train_q,
        x_val_q,
        x_test_q,
        y_train_q,
        y_val_q,
        y_test_q,
        train_loader_q,
        val_loader_q,
        test_loader_q,
    ) = quantum_data

    return {
        "input_dim": input_dim,
        "output_dim": output_dim,
        "train_loader": train_loader_q,
        "val_loader": val_loader_q,
        "test_loader": test_loader_q,
    }


def final_retrain_selected_circuit(qiskit_circuit, openml_dataset_id: int, n_qubits: int, seed: int):
    data = build_quantum_dataloaders(openml_dataset_id, n_qubits, seed)

    model_q = QuantumNN(
        ansatz=qiskit_circuit,
        n_qubits=data["input_dim"],
        num_classes=data["output_dim"],
        use_gpu=USE_GPU,
        gradient_method="guided_spsa",
        seed=seed,
    )

    optimizer_q = optim.Adam(model_q.parameters(), lr=BENCHRL_CONFIG["final_train_lr"])
    scheduler_q = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer_q,
        mode="min",
        factor=0.3,
        patience=max(1, BENCHRL_CONFIG["final_train_epochs"] // 5),
        min_lr=1e-4,
        verbose=False,
    )

    t0 = time.perf_counter()
    model_q.fit(
        data["train_loader"],
        data["val_loader"],
        epochs=BENCHRL_CONFIG["final_train_epochs"],
        optimizer=optimizer_q,
        scheduler=scheduler_q,
        verbose=VERBOSE_ON_FIT,
        eval_every=2,
    )
    final_train_time_sec = time.perf_counter() - t0

    return final_train_time_sec


def run_timed_rl_qas(dataset_name, openml_dataset_id, n_qubits, seed, timings_dir):
    config_stem = f"{dataset_name}_coblya_{n_qubits}q_VQC"
    config_path = RL_CONFIG_DIR / f"{config_stem}.cfg"

    if not config_path.exists():
        raise FileNotFoundError(f"Config not found: {config_path}")

    args_dict = {
        "config": str(config_path),
        "output_fp": str(BENCHRL_TIMING_ROOT / dataset_name / f"seed_{seed}" / f"{n_qubits}qubits"),
        "experiment_name": "TPPO",
    }
    args = Namespace(**args_dict)

    results_path = Path(args.output_fp)
    results_path.mkdir(parents=True, exist_ok=True)

    device = torch.device("cpu")
    conf = get_config(args.experiment_name, args.config)

    conf["openml"]["dataset_id"] = openml_dataset_id
    conf["env"]["num_qubits"] = n_qubits

    environment = CircuitEnv(conf, seed, device=device)

    initial_state = environment.reset()
    base_state_size = initial_state.shape[0]
    effective_state_size = base_state_size
    if conf["agent"]["en_state"]:
        effective_state_size += 1
    if "threshold_in_state" in conf["agent"].keys() and conf["agent"]["threshold_in_state"]:
        effective_state_size += 1

    agent = agents.__dict__[conf["agent"]["agent_type"]].__dict__[conf["agent"]["agent_class"]](
        conf, environment.action_size, effective_state_size, device
    )
    agent.saver = Saver(str(results_path), seed)

    search_t0 = time.perf_counter()
    train(
        agent,
        environment,
        BENCHRL_CONFIG["pilot_episodes"],
        seed,
        str(results_path),
        conf["env"]["accept_err"],
        conf,
    )
    measured_pilot_rl_training_time_sec = time.perf_counter() - search_t0

    extract_t0 = time.perf_counter()
    qulacs_circuit = greedy_eval_episode(environment, agent, device, conf)
    greedy_circuit_extraction_time_sec = time.perf_counter() - extract_t0

    if qulacs_circuit is None:
        raise RuntimeError("Could not retrieve circuit from greedy_eval_episode.")

    qiskit_circuit = convert_qulacs_to_qiskit(qulacs_circuit)

    estimated_full_rl_training_time_sec = (
        measured_pilot_rl_training_time_sec
        * (BENCHRL_CONFIG["full_episodes"] / BENCHRL_CONFIG["pilot_episodes"])
    )

    reported_search_time_sec = (
        estimated_full_rl_training_time_sec + greedy_circuit_extraction_time_sec
    )

    measured_final_train_time_sec = final_retrain_selected_circuit(
        qiskit_circuit=qiskit_circuit,
        openml_dataset_id=openml_dataset_id,
        n_qubits=n_qubits,
        seed=seed,
    )

    reported_train_time_sec = measured_final_train_time_sec
    reported_total_time_sec = reported_search_time_sec + reported_train_time_sec

    output_data = {
        "method": "BenchRL-QAS-TPPO",
        "dataset": dataset_name,
        "seed": int(seed),
        "qubits": int(n_qubits),
        "runtime_table_sec": {
            "search": float(reported_search_time_sec),
            "train": float(reported_train_time_sec),
            "total": float(reported_total_time_sec),
        },
        "timings_sec": {
            "measured_pilot_rl_training_time_sec": float(measured_pilot_rl_training_time_sec),
            "estimated_full_rl_training_time_sec": float(estimated_full_rl_training_time_sec),
            "greedy_circuit_extraction_time_sec": float(greedy_circuit_extraction_time_sec),
            "measured_final_train_time_sec": float(measured_final_train_time_sec),
        },
        "pilot_config": {
            "episodes": int(BENCHRL_CONFIG["pilot_episodes"]),
        },
        "full_config": {
            "episodes": int(BENCHRL_CONFIG["full_episodes"]),
            "final_train_epochs": int(BENCHRL_CONFIG["final_train_epochs"]),
        },
    }

    os.makedirs(timings_dir, exist_ok=True)
    out_fp = os.path.join(timings_dir, "final_results.json")
    with open(out_fp, "w") as f:
        json.dump(output_data, f, indent=2)

    print(f"[INFO] Saved timing-only results to {out_fp}")


if __name__ == "__main__":
    for exp in iter_experiments():
        set_seed(exp["seed"])
        run_timed_rl_qas(
            dataset_name=exp["dataset_name"],
            openml_dataset_id=exp["dataset_id"],
            n_qubits=exp["n_qubits"],
            seed=exp["seed"],
            timings_dir=str(make_timings_dir("BenchRL-QAS-TPPO", exp["dataset_name"], exp["seed"], exp["n_qubits"])),
        )

[env] Loading OpenML data for dataset ID: 61
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
[env] OpenML splits → train (88, 4), test (30, 4)
Dataset name: iris
Total features: 4, Dropped Categorical features: 0, Remaining features: 4
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/iris/seed_0/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
[env] OpenML splits → train (106, 4), test (36, 4)
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/wine/seed_0/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
[env] OpenML splits → train (460, 4), test (154, 4)
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 4 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/diabetes/seed_0/4qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
[env] OpenML splits → train (106, 6), test (36, 6)
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/wine/seed_0/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
[env] OpenML splits → train (460, 6), test (154, 6)
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Classical data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 6 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/diabetes/seed_0/6qubits/final_results.json
[env] Loading OpenML data for dataset ID: 187
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
[env] OpenML splits → train (106, 8), test (36, 8)
Dataset name: wine
Total features: 13, Dropped Categorical features: 0, Remaining features: 13
Classical data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Quantum data reduced to 8 dimensions using PCA.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/wine/seed_0/8qubits/final_results.json
[env] Loading OpenML data for dataset ID: 37
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
[env] OpenML splits → train (460, 8), test (154, 8)
Dataset name: diabetes
Total features: 8, Dropped Categorical features: 0, Remaining features: 8
Configuring DataLoader for CPU.
Configuring DataLoader for CPU.
Initialized QuantumNN on device: cpu

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:59: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

[INFO] Saved timing-only results to /Users/larryhh/Documents/PhD/Projects/weight_matrix_informed_circuit_design/utils/benchmarks/timing_results/BenchRL-QAS-TPPO/diabetes/seed_0/8qubits/final_results.json

In [24]:
import json
from pathlib import Path
from collections import defaultdict

import pandas as pd

BENCHMARKS_DIR = Path.cwd()
TIMING_ROOT = BENCHMARKS_DIR / "timing_results"

METHOD_DIRS = {
    "QuantumDARTS": "QuantumDARTS",
    "TF-QAS": "TF-QAS",
    "BenchRL-QAS (TPPO)": "BenchRL-QAS-TPPO",
}

TARGET_ROWS = [
    ("iris", 4),
    ("wine", 4),
    ("wine", 6),
    ("wine", 8),
    ("diabetes", 4),
    ("diabetes", 6),
    ("diabetes", 8),
]

DATASET_LABELS = {
    "iris": "Iris",
    "wine": "Wine",
    "diabetes": "Diabetes",
}


def load_all_timing_results():
    rows = []

    for method_label, method_dirname in METHOD_DIRS.items():
        method_root = TIMING_ROOT / method_dirname
        if not method_root.exists():
            print(f"[WARN] Missing method folder: {method_root}")
            continue

        for dataset_dir in method_root.iterdir():
            if not dataset_dir.is_dir():
                continue

            dataset = dataset_dir.name.lower()

            for seed_dir in dataset_dir.glob("seed_*"):
                seed_str = seed_dir.name.replace("seed_", "")
                try:
                    seed = int(seed_str)
                except ValueError:
                    seed = seed_str

                for qubit_dir in seed_dir.glob("*qubits"):
                    result_fp = qubit_dir / "final_results.json"
                    if not result_fp.exists():
                        continue

                    try:
                        qubits = int(qubit_dir.name.replace("qubits", ""))
                    except ValueError:
                        continue

                    with open(result_fp, "r") as f:
                        data = json.load(f)

                    runtime = data.get("runtime_table_sec", {})
                    rows.append({
                        "method": method_label,
                        "dataset": dataset,
                        "qubits": qubits,
                        "seed": seed,
                        "search": runtime.get("search"),
                        "train": runtime.get("train"),
                        "total": runtime.get("total"),
                    })

    return pd.DataFrame(rows)


def summarise_timings(df):
    if df.empty:
        return df

    grouped = (
        df.groupby(["method", "dataset", "qubits"], as_index=False)
          .agg(
              search_mean=("search", "mean"),
              search_std=("search", "std"),
              train_mean=("train", "mean"),
              train_std=("train", "std"),
              total_mean=("total", "mean"),
              total_std=("total", "std"),
              n=("seed", "count"),
          )
    )
    return grouped


def fmt(x):
    if pd.isna(x):
        return "[\\;]"
    return f"{x:.2f}"


def get_cell(summary_df, method, dataset, qubits, metric):
    sub = summary_df[
        (summary_df["method"] == method) &
        (summary_df["dataset"] == dataset) &
        (summary_df["qubits"] == qubits)
    ]
    if sub.empty:
        return "[\\;]"
    return fmt(sub.iloc[0][f"{metric}_mean"])


def build_latex_rows(summary_df):
    rows = []

    for dataset, qubits in TARGET_ROWS:
        dataset_label = DATASET_LABELS[dataset]

        wi = ["[\\;]", "[\\;]", "[\\;]"]  # still placeholders
        tf = [
            get_cell(summary_df, "TF-QAS", dataset, qubits, "search"),
            get_cell(summary_df, "TF-QAS", dataset, qubits, "train"),
            get_cell(summary_df, "TF-QAS", dataset, qubits, "total"),
        ]
        qd = [
            get_cell(summary_df, "QuantumDARTS", dataset, qubits, "search"),
            get_cell(summary_df, "QuantumDARTS", dataset, qubits, "train"),
            get_cell(summary_df, "QuantumDARTS", dataset, qubits, "total"),
        ]
        rl = [
            get_cell(summary_df, "BenchRL-QAS (TPPO)", dataset, qubits, "search"),
            get_cell(summary_df, "BenchRL-QAS (TPPO)", dataset, qubits, "train"),
            get_cell(summary_df, "BenchRL-QAS (TPPO)", dataset, qubits, "total"),
        ]

        line = (
            f"{dataset_label} & {qubits} "
            f"& {wi[0]} & {wi[1]} & {wi[2]} "
            f"& {tf[0]} & {tf[1]} & {tf[2]} "
            f"& {qd[0]} & {qd[1]} & {qd[2]} "
            f"& {rl[0]} & {rl[1]} & {rl[2]} \\\\"
        )
        rows.append(line)

        if (dataset, qubits) == ("iris", 4):
            rows.append(r"\midrule")
        elif (dataset, qubits) == ("wine", 8):
            rows.append(r"\midrule")

    return rows

In [25]:
df_raw = load_all_timing_results()
df_summary = summarise_timings(df_raw)

print("Raw timing rows:")
display(df_raw.sort_values(["method", "dataset", "qubits", "seed"]))

print("\nSummary:")
display(df_summary.sort_values(["dataset", "qubits", "method"]))

Raw timing rows:

,method,dataset,qubits,seed,search,train,total
68,BenchRL-QAS (TPPO),diabetes,2,0,3081.032123,62.389060,3143.421183
70,BenchRL-QAS (TPPO),diabetes,4,0,3941.260878,137.526251,4078.787129
69,BenchRL-QAS (TPPO),diabetes,6,0,3575.424443,29.278730,3604.703173
71,BenchRL-QAS (TPPO),diabetes,8,0,6163.178594,38.405320,6201.583914
62,BenchRL-QAS (TPPO),iris,2,0,410.126956,16.061725,426.188681
63,BenchRL-QAS (TPPO),iris,4,0,583.671528,36.383389,620.054917
64,BenchRL-QAS (TPPO),wine,2,0,747.199762,20.173849,767.373611
66,BenchRL-QAS (TPPO),wine,4,0,636.907313,29.175819,666.083132
65,BenchRL-QAS (TPPO),wine,6,0,739.169842,6.467650,745.637491
67,BenchRL-QAS (TPPO),wine,8,0,757.960049,9.633186,767.593235
34,QuantumDARTS,diabetes,2,0,593.546828,419.523108,1013.069936
36,QuantumDARTS,diabetes,4,0,1054.065227,563.523600,1617.588827
32,QuantumDARTS,diabetes,4,1,930.765676,481.486258,1412.251935
23,QuantumDARTS,diabetes,4,2,947.082137,483.160713,1430.242850
29,QuantumDARTS,diabetes,4,3,1106.912922,621.647116,1728.560038
26,QuantumDARTS,diabetes,4,4,1007.838044,672.454993,1680.293037
35,QuantumDARTS,diabetes,6,0,1786.365727,800.743586,2587.109312
31,QuantumDARTS,diabetes,6,1,1570.681757,671.237682,2241.919439
22,QuantumDARTS,diabetes,6,2,1591.581091,683.300990,2274.882080
28,QuantumDARTS,diabetes,6,3,1854.672718,896.263876,2750.936594
25,QuantumDARTS,diabetes,6,4,1692.013138,944.332116,2636.345253
37,QuantumDARTS,diabetes,8,0,2844.342545,1197.839603,4042.182148
33,QuantumDARTS,diabetes,8,1,2490.592236,988.890411,3479.482648
24,QuantumDARTS,diabetes,8,2,2519.997460,998.475748,3518.473208
30,QuantumDARTS,diabetes,8,3,2923.403999,1319.853680,4243.257679
27,QuantumDARTS,diabetes,8,4,2686.919495,1414.230573,4101.150068
4,QuantumDARTS,iris,2,0,537.868510,81.421464,619.289974
5,QuantumDARTS,iris,4,0,958.326766,109.081888,1067.408655
3,QuantumDARTS,iris,4,1,877.614097,93.018237,970.632334
0,QuantumDARTS,iris,4,2,898.475542,93.590609,992.066151
2,QuantumDARTS,iris,4,3,1054.247380,121.294414,1175.541794
1,QuantumDARTS,iris,4,4,959.872753,130.689310,1090.562063
18,QuantumDARTS,wine,2,0,508.331890,97.487390,605.819279
20,QuantumDARTS,wine,4,0,907.506438,131.834448,1039.340886
16,QuantumDARTS,wine,4,1,799.172817,111.243718,910.416535
7,QuantumDARTS,wine,4,2,806.920538,112.157343,919.077881
13,QuantumDARTS,wine,4,3,930.199203,145.381388,1075.580591
10,QuantumDARTS,wine,4,4,868.666269,156.166002,1024.832271
19,QuantumDARTS,wine,6,0,1540.335120,186.599105,1726.934224
15,QuantumDARTS,wine,6,1,1359.420240,156.335608,1515.755848
6,QuantumDARTS,wine,6,2,1368.958409,158.410232,1527.368640
12,QuantumDARTS,wine,6,3,1594.649904,208.421729,1803.071633
9,QuantumDARTS,wine,6,4,1463.945276,217.882726,1681.828002
21,QuantumDARTS,wine,8,0,2446.091516,276.884026,2722.975542
17,QuantumDARTS,wine,8,1,2164.315800,228.801849,2393.117649
8,QuantumDARTS,wine,8,2,2166.502700,232.035364,2398.538064
14,QuantumDARTS,wine,8,3,2519.156896,305.620428,2824.777324
11,QuantumDARTS,wine,8,4,2308.162046,326.604416,2634.766462
58,TF-QAS,diabetes,2,0,32851.550723,607.265975,33458.816698
60,TF-QAS,diabetes,4,0,42521.237103,862.951414,43384.188517
56,TF-QAS,diabetes,4,1,43136.168848,873.118076,44009.286924
53,TF-QAS,diabetes,4,2,43372.747246,775.476455,44148.223701
59,TF-QAS,diabetes,6,0,64047.562159,1199.555802,65247.117961
55,TF-QAS,diabetes,6,1,62513.060203,1158.934363,63671.994565
52,TF-QAS,diabetes,6,2,64936.666564,1291.826189,66228.492753
61,TF-QAS,diabetes,8,0,94854.478672,1883.759764,96738.238436
57,TF-QAS,diabetes,8,1,93018.861251,1754.429720,94773.290971
54,TF-QAS,diabetes,8,2,95548.719206,1759.489812,97308.209018
40,TF-QAS,iris,2,0,7133.729812,142.059532,7275.789344
41,TF-QAS,iris,4,0,9451.902075,166.168877,9618.070952
39,TF-QAS,iris,4,1,9224.949343,170.628613,9395.577956
38,TF-QAS,iris,4,2,9114.246892,168.859124,9283.106016
48,TF-QAS,wine,2,0,8340.567314,140.412853,8480.980166
50,TF-QAS,wine,4,0,10592.477679,199.209988,10791.687667
46,TF-QAS,wine,4,1,10872.269026,206.051070,11078.320096
43,TF-QAS,wine,4,2,10793.321766,203.663954,10996.985720
49,TF-QAS,wine,6,0,14985.775591,272.636297,15258.411888
45,TF-QAS,wine,6,1,15003.849679,269.633275,15273.482954
42,TF-QAS,wine,6,2,15648.562784,276.106150,15924.668933
51,TF-QAS,wine,8,0,22978.152175,396.940018,23375.092193
47,TF-QAS,wine,8,1,21877.005836,456.334501,22333.340337
44,TF-QAS,wine,8,2,22862.538095,404.403740,23266.941835

Summary:

,method,dataset,qubits,search_mean,search_std,train_mean,train_std,total_mean,total_std,n
0,BenchRL-QAS (TPPO),diabetes,2,3081.032123,NaN,62.389060,NaN,3143.421183,NaN,1
10,QuantumDARTS,diabetes,2,593.546828,NaN,419.523108,NaN,1013.069936,NaN,1
20,TF-QAS,diabetes,2,32851.550723,NaN,607.265975,NaN,33458.816698,NaN,1
1,BenchRL-QAS (TPPO),diabetes,4,3941.260878,NaN,137.526251,NaN,4078.787129,NaN,1
11,QuantumDARTS,diabetes,4,1009.332801,73.438822,564.454536,84.303584,1573.787337,144.840714,5
21,TF-QAS,diabetes,4,43010.051066,439.541411,837.181982,53.679785,43847.233047,406.981001,3
2,BenchRL-QAS (TPPO),diabetes,6,3575.424443,NaN,29.278730,NaN,3604.703173,NaN,1
12,QuantumDARTS,diabetes,6,1699.062886,122.392765,799.175650,122.774226,2498.238536,227.164794,5
22,TF-QAS,diabetes,6,63832.429642,1226.041781,1216.772118,68.098168,65049.201760,1289.689444,3
3,BenchRL-QAS (TPPO),diabetes,8,6163.178594,NaN,38.405320,NaN,6201.583914,NaN,1
13,QuantumDARTS,diabetes,8,2693.051147,191.654840,1183.858003,189.829379,3876.909150,352.928657,5
23,TF-QAS,diabetes,8,94474.019710,1307.136980,1799.226432,73.251719,96273.246142,1329.893135,3
4,BenchRL-QAS (TPPO),iris,2,410.126956,NaN,16.061725,NaN,426.188681,NaN,1
14,QuantumDARTS,iris,2,537.868510,NaN,81.421464,NaN,619.289974,NaN,1
24,TF-QAS,iris,2,7133.729812,NaN,142.059532,NaN,7275.789344,NaN,1
5,BenchRL-QAS (TPPO),iris,4,583.671528,NaN,36.383389,NaN,620.054917,NaN,1
15,QuantumDARTS,iris,4,949.707308,68.790230,109.534892,16.680985,1059.242199,82.063314,5
25,TF-QAS,iris,4,9263.699437,172.130569,168.552205,2.245653,9432.251641,170.467288,3
6,BenchRL-QAS (TPPO),wine,2,747.199762,NaN,20.173849,NaN,767.373611,NaN,1
16,QuantumDARTS,wine,2,508.331890,NaN,97.487390,NaN,605.819279,NaN,1
26,TF-QAS,wine,2,8340.567314,NaN,140.412853,NaN,8480.980166,NaN,1
7,BenchRL-QAS (TPPO),wine,4,636.907313,NaN,29.175819,NaN,666.083132,NaN,1
17,QuantumDARTS,wine,4,862.493053,58.622080,131.356580,19.909602,993.849633,74.600979,5
27,TF-QAS,wine,4,10752.689490,144.253374,202.975004,3.472188,10955.664494,147.716350,3
8,BenchRL-QAS (TPPO),wine,6,739.169842,NaN,6.467650,NaN,745.637491,NaN,1
18,QuantumDARTS,wine,6,1465.461790,103.507967,185.529880,28.105460,1650.991670,125.914502,5
28,TF-QAS,wine,6,15212.729351,377.550995,272.791907,3.239242,15485.521258,380.387690,3
9,BenchRL-QAS (TPPO),wine,8,757.960049,NaN,9.633186,NaN,767.593235,NaN,1
19,QuantumDARTS,wine,8,2320.845792,160.855596,273.989217,43.529578,2594.835008,193.720397,5
29,TF-QAS,wine,8,22572.565369,605.139613,419.226086,32.352784,22991.791455,572.793620,3

In [14]:
latex_rows = build_latex_rows(df_summary)
print("\n".join(latex_rows))

Iris & 4 & [\;] & [\;] & [\;] & 9263.70 & 168.55 & 9432.25 & 949.71 & 109.53 & 1059.24 & 583.67 & 36.38 & 620.05 \\
\midrule
Wine & 4 & [\;] & [\;] & [\;] & 10752.69 & 202.98 & 10955.66 & 862.49 & 131.36 & 993.85 & 636.91 & 29.18 & 666.08 \\
Wine & 6 & [\;] & [\;] & [\;] & 15212.73 & 272.79 & 15485.52 & 1465.46 & 185.53 & 1650.99 & 739.17 & 6.47 & 745.64 \\
Wine & 8 & [\;] & [\;] & [\;] & 22572.57 & 419.23 & 22991.79 & 2320.85 & 273.99 & 2594.84 & 757.96 & 9.63 & 767.59 \\
\midrule
Diabetes & 4 & [\;] & [\;] & [\;] & 43010.05 & 837.18 & 43847.23 & 1009.33 & 564.45 & 1573.79 & 3941.26 & 137.53 & 4078.79 \\
Diabetes & 6 & [\;] & [\;] & [\;] & 63832.43 & 1216.77 & 65049.20 & 1699.06 & 799.18 & 2498.24 & 3575.42 & 29.28 & 3604.70 \\
Diabetes & 8 & [\;] & [\;] & [\;] & 94474.02 & 1799.23 & 96273.25 & 2693.05 & 1183.86 & 3876.91 & 6163.18 & 38.41 & 6201.58 \\

In [26]:
pd.set_option("display.max_rows", None)

df_raw["search_min"] = df_raw["search"] / 60
df_raw["train_min"] = df_raw["train"] / 60
df_raw["total_min"] = df_raw["total"] / 60

In [30]:
df_raw[(df_raw['dataset'] == 'wine') & (df_raw['qubits'] == 8)]

,method,dataset,qubits,seed,search,train,total,search_min,train_min,total_min
8,QuantumDARTS,wine,8,2,2166.502700,232.035364,2398.538064,36.108378,3.867256,39.975634
11,QuantumDARTS,wine,8,4,2308.162046,326.604416,2634.766462,38.469367,5.443407,43.912774
14,QuantumDARTS,wine,8,3,2519.156896,305.620428,2824.777324,41.985948,5.093674,47.079622
17,QuantumDARTS,wine,8,1,2164.315800,228.801849,2393.117649,36.071930,3.813364,39.885294
21,QuantumDARTS,wine,8,0,2446.091516,276.884026,2722.975542,40.768192,4.614734,45.382926
44,TF-QAS,wine,8,2,22862.538095,404.403740,23266.941835,381.042302,6.740062,387.782364
47,TF-QAS,wine,8,1,21877.005836,456.334501,22333.340337,364.616764,7.605575,372.222339
51,TF-QAS,wine,8,0,22978.152175,396.940018,23375.092193,382.969203,6.615667,389.584870
67,BenchRL-QAS (TPPO),wine,8,0,757.960049,9.633186,767.593235,12.632667,0.160553,12.793221